---
#
# Firewall configuration.
#
iptables_allow_icmp_inbound:
  - "{{ all.ip_addresses['umcg']['net1'] }}"
  - "{{ all.ip_addresses['umcg']['net2'] }}"
  - "{{ all.ip_addresses['umcg']['net3'] }}"
  - "{{ all.ip_addresses['umcg']['net4'] }}"
  - "{{ all.ip_addresses['rug']['bwp_net'] }}"
  - "{{ all.ip_addresses['rug']['operator'] }}"
  - "{{ all.ip_addresses['gcc']['cloud_net'] }}"
  - "{{ all.ip_addresses['gcc']['step01'] }}"
  - "{{ hyperchicken_cluster.ip_addresses['portal']['external_unfiltered'] }}"
  - "{{ nibbler_cluster.ip_addresses['tunnel']['vlan16'] }}"
  - "{{ talos_cluster.ip_addresses['reception']['vlan16'] }}"
  - "{{ vaxtron_cluster.ip_addresses['foyer']['external'] }}"
iptables_allow_ssh_inbound:
  - "{{ hyperchicken_cluster.ip_addresses['portal']['external_unfiltered'] }}"
  - "{{ nibbler_cluster.ip_addresses['tunnel']['vlan16'] }}"
  - "{{ talos_cluster.ip_addresses['reception']['vlan16'] }}"
  - "{{ vaxtron_cluster.ip_addresses['foyer']['external'] }}"
  - "{{ all.ip_addresses['gcc']['step01'] }}"
iptables_allow_ssh_outbound:
  - "{{ hyperchicken_cluster.ip_addresses['portal']['external_unfiltered'] }}"
  - "{{ nibbler_cluster.ip_addresses['tunnel']['vlan16'] }}"
  - "{{ talos_cluster.ip_addresses['reception']['vlan16'] }}"
  - "{{ vaxtron_cluster.ip_addresses['foyer']['external'] }}"
  - "{{ all.ip_addresses['gcc']['step01'] }}"
#
# Enforce that build servers use `yum_repos` for defining repositories, since they cannot use Pulp.
#
repo_manager: 'none'
#
# Configure limited subset of repos: Only relevant for cluster machines that do not use Pulp for repo management:
# E.g. they must have
#      repo_manager: 'none'
# configured for the list below to have any affect.
# Listing the repo ID here does not mean the repo will be enabled!
# It means the repo config as listed in the yum_repos variable from
#     group_vars/all/repos.yml
# will be applied to the machine, which can include instructions for both enabling or disabling a repo.
#
yum_repos_deployed_on_clients:
  alma9: "{{ yum_repos['alma9']
              | selectattr('tags', 'defined')
              | selectattr('tags', 'intersect', ['core', 'epel', 'rsyslog', 'irods'])
              | map(attribute='id') }}"
...
