---
slurm_local_scratch_dir: '/local'
autoupdate_enabled: false
#
# Do not use fail2ban for machines behind the jumphost to prevent the jumphost from getting blocked.
# We already have fail2ban on the jumphost to block external IPs the produce too many failed logins.
#
basic_security_fail2ban_enabled: false
#
# Configure limited subset of repos: Only relevant for cluster machines that do not use Pulp for repo management:
# E.g. they must have
#      repo_manager: 'none'
# configured for the list below to have any affect.
# Listing the repo ID here does not mean the repo will be enabled!
# It means the repo config as listed in the yum_repos variable from
#     group_vars/all/repos.yml
# will be applied to the machine, which can include instructions for both enabling or disabling a repo.
#
yum_repos_deployed_on_clients:
  oracle8: "{{ yum_repos['oracle8']
              | selectattr('tags', 'defined')
              | selectattr('tags', 'intersect', ['core', 'epel', 'uek', 'rsyslog'])
              | map(attribute='id') }}"
  alma9: "{{ yum_repos['alma9']
              | selectattr('tags', 'defined')
              | selectattr('tags', 'intersect', ['core', 'epel', 'rsyslog', 'irods'])
              | map(attribute='id') }}"
  rocky9: "{{ yum_repos['rocky9']
              | selectattr('tags', 'defined')
              | selectattr('tags', 'intersect', ['core', 'epel', 'security', 'rsyslog', 'irods'])
              | map(attribute='id') }}"
...
