---
os_distribution: 'alma9'
#
# Enforce that docs servers use `yum_repos` for defining repositories, since they cannot use Pulp.
#
repo_manager: 'none'
#
# Configure limited subset of repos.
# Listing the repo ID here does not mean the repo will be enabled!
# It means the repo config as listed in the yum_repos variable from
#     group_vars/all/repos.yml
# will be applied to the machine, which can include instructions for both enabling or disabling a repo.
#
yum_repos_deployed_on_clients:
  alma9: "{{ yum_repos['alma9']
              | selectattr('tags', 'defined')
              | selectattr('tags', 'intersect', ['core', 'epel', 'rsyslog'])
              | map(attribute='id') }}"
#
# Firewall configuration.
#
iptables_allow_icmp_inbound:
  - "{{ all.ip_addresses['umcg']['net1'] }}"
  - "{{ all.ip_addresses['umcg']['net2'] }}"
  - "{{ all.ip_addresses['umcg']['net3'] }}"
  - "{{ all.ip_addresses['umcg']['net4'] }}"
  - "{{ all.ip_addresses['rug']['bwp_net'] }}"
  - "{{ all.ip_addresses['rug']['operator'] }}"
  - "{{ all.ip_addresses['gcc']['cloud_net'] }}"
  - "{{ hyperchicken_cluster.ip_addresses['portal']['external_unfiltered'] }}"
  - "{{ nibbler_cluster.ip_addresses['tunnel']['vlan16'] }}"
  - "{{ talos_cluster.ip_addresses['reception']['vlan16'] }}"
  - "{{ vaxtron_cluster.ip_addresses['foyer']['external'] }}"
  - "{{ wingedhelix_cluster.ip_addresses['wh-porch']['vlan16'] }}"
  - "{{ betabarrel_cluster.ip_addresses['bb-porch']['vlan16'] }}"
  - "{{ copperfist_cluster.ip_addresses['cf-porch']['external'] }}"
iptables_allow_ssh_inbound:
  - "{{ hyperchicken_cluster.ip_addresses['portal']['external_unfiltered'] }}"
  - "{{ nibbler_cluster.ip_addresses['tunnel']['vlan16'] }}"
  - "{{ talos_cluster.ip_addresses['reception']['vlan16'] }}"
  - "{{ vaxtron_cluster.ip_addresses['foyer']['external'] }}"
  - "{{ wingedhelix_cluster.ip_addresses['wh-porch']['vlan16'] }}"
  - "{{ betabarrel_cluster.ip_addresses['bb-porch']['vlan16'] }}"
  - "{{ copperfist_cluster.ip_addresses['cf-porch']['external'] }}"
iptables_allow_http_inbound:
  - ANY
iptables_allow_https_inbound:
  - ANY
fqdn: docs.gcc.rug.nl
https_certificate_file: "{{ playbook_dir }}/files/{{ inventory_hostname }}/{{ fqdn }}.pem"
https_private_key_file: "{{ playbook_dir }}/files/{{ inventory_hostname }}/{{ fqdn }}.key"
https_chain_file: "{{ playbook_dir }}/files/{{ inventory_hostname }}/HARICA-GEANT-TLS-ECC-Certificate-bundle.pem"
...
