---
ip_addresses:
  alma9-build:
    build_internal_management:
      address: 10.10.1.249
      netmask: /32
      publicly_exposed: true  # This internal IP is linked to a public (floating) IP.
    vlan16:
      address: 195.169.22.135
      netmask: /32
      fqdn: 'NXDOMAIN'
  build_internal_management-vlan16-router:
    build_internal_management:
      address: 10.10.1.1
      netmask: /32
    vlan16:
      address: 195.169.22.183
      netmask: /32
      fqdn: 'NXDOMAIN'
...
