---
- hosts:
    - jumphost
  roles:
    - basic_security
- hosts:
    - build_server
    - cluster
    - chaperone,!mit_chaperone
    - data_transfer
    - docs
    - irods
    - jenkins
    - logs
    - repo
    - repo_servers
    - silo
  roles:
    - basic_security
...
