- name: Mount extra local file systems.
  hosts:
     - nfs_server
     - compute_node
     - deploy_admin_interface
     - data_transfer
     - chaperone
     - silo_server
     - repo_servers
  roles:
     - role: local_storage
       when: local_mounts is defined and local_mounts | length > 0
...
