---
- hosts:
    - jumphost
  roles:
    - remove

- hosts:
    - repo
    - cluster
    - chaperone,!mit_chaperone
    - docs
    - irods
    - logs
    - repo_servers
    - silo
  roles:
    - remove
...
