---
- name: Configure ssh and sshfs
  ansible.builtin.include_tasks:
    file: automounts.yml
  when:
    - remote_archive is defined
    - inventory_hostname in groups['user_interface'] | default([])

- name: Configure ssh and sshfs
  ansible.builtin.include_tasks:
    file: sshfs.yml
  when:
    - remote_archive is defined
    - inventory_hostname in groups['user_interface'] | default([])

- name: Configure file recall (staging) from remote system
  ansible.builtin.include_tasks:
    file: recall.yml
  when:
    - remote_archive is defined
    - inventory_hostname in groups['user_interface'] | default([])

- name: Install file size check script
  ansible.builtin.copy:
    src: "files/arc_sizecheck"
    dest: /usr/local/bin/arc_sizecheck
    mode: "0755"
    owner: root
    group: root
  when:
    - remote_archive is defined
    - inventory_hostname in groups['user_interface'] | default([])
  become: true
...
