---
#
# Additional notes about these security groups are in the ../README.md
#
# Open: the security group that allows all traffic - needed for subnets.
#       (see README.md for why this is needed)
#
- name: "Create {{ stack_prefix }}_open security group."
  azure.azcollection.azure_rm_securitygroup:
    name: "{{ stack_prefix }}_open"
    rules:
      - name: Any
        protocol: "*"
        destination_port_range: "*"
        source_address_prefix: '*'
        access: Allow
        priority: 100
    purge_rules: true
    resource_group: "{{ azure_resource_group }}"
#
# Jumphost: receive 22 and 443 from anywhere, block ICMP
#
- name: "Create {{ stack_prefix }}_jumphosts security group."
  azure.azcollection.azure_rm_securitygroup:
    name: "{{ stack_prefix }}_jumphosts"
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        source_address_prefix: '*'
        access: Allow
        priority: 101
      - name: SSH_fallback
        protocol: Tcp
        destination_port_range: 443
        source_address_prefix: '*'
        access: Allow
        priority: 102
      - name: ICMP
        protocol: Icmp
        source_address_prefix: '*'
        access: Deny
        priority: 103
    purge_rules: true
    resource_group: "{{ azure_resource_group }}"
#
# Cluster: allow connection only from nodes in the same network.
#
- name: "Create {{ stack_prefix }}_cluster security group."
  azure.azcollection.azure_rm_securitygroup:
    name: "{{ security_group_name }}"
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        source_address_prefix: "{{ azure_network['cidr'] }}"
        access: Allow
        priority: 201
      - name: SSH_fallback
        protocol: Tcp
        destination_port_range: 443
        source_address_prefix: "{{ azure_network['cidr'] }}"
        access: Allow
        priority: 202
      - name: ICMP
        protocol: Icmp
        source_address_prefix: "{{ azure_network['cidr'] }}"
        access: Allow
        priority: 203
    purge_rules: true
    resource_group: "{{ azure_resource_group }}"
  vars:
    security_group_name: "{{ stack_prefix }}_cluster"
    network_name_query: "* | [?azure_flavor] | [].host_networks[?security_group=='{{ security_group_name }}'].name"
    network_names_of_all_hosts_created_in_azure_using_this_security_group: "{{ hostvars
        | json_query(network_name_query)
        | flatten
        | unique }}"
  loop: "{{ azure_networks
            | map(attribute='name')
            | intersect(network_names_of_all_hosts_created_in_azure_using_this_security_group)
            | default([]) }}"
  loop_control:
    loop_var: azure_network
  when: security_group_name in security_group_names_of_all_hosts_created_in_azure
#
# Logs: allow external connections
#
- name: "Create {{ stack_prefix }}_logservers security group."
  azure.azcollection.azure_rm_securitygroup:
    name: "{{ security_group_name }}"
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        source_address_prefix: "*"
        direction: Inbound
        access: Allow
        priority: 101
      - name: SSH_fallback
        protocol: Tcp
        destination_port_range: 443
        source_address_prefix: "*"
        direction: Inbound
        access: Allow
        priority: 102
      - name: Rsyslog
        protocol: Tcp
        destination_port_range: 41514
        source_address_prefix: "*"
        direction: Inbound
        access: Allow
        priority: 103
      - name: ICMP
        protocol: Icmp
        source_address_prefix: "*"
        direction: Inbound
        access: Allow
        priority: 104
    purge_rules: true
    resource_group: "{{ azure_resource_group }}"
  vars:
    security_group_name: "{{ stack_prefix }}_logservers"
  when: security_group_name in security_group_names_of_all_hosts_created_in_azure
#
# Repository: receive 8443 from anywhere, block ICMP
#
- name: "Create {{ stack_prefix }}_repository security group."
  azure.azcollection.azure_rm_securitygroup:
    name: "{{ stack_prefix }}_repository"
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        source_address_prefix: '*'
        access: Allow
        priority: 101
      - name: SSH_fallback
        protocol: Tcp
        destination_port_range: 443
        source_address_prefix: '*'
        access: Allow
        priority: 102
      - name: ICMP
        protocol: Icmp
        source_address_prefix: '*'
        access: Deny
        priority: 103
      - name: HTTPs
        protocol: Tcp
        destination_port_range: 8443
        source_address_prefix: '*'
        access: Allow
        priority: 104
    purge_rules: true
    resource_group: "{{ azure_resource_group }}"
...
