---
#
# Important: maintain correct handler order.
# Handlers are executed in the order in which they are defined
# and not in the order in which they are listed in a "notify: handler_name" statement!
#
- name: Rebuild GRUB config.
  ansible.builtin.shell: |
         set -e
         set -u
         set -o pipefail
         timestamp="$(date '+%Y-%m-%dT%H:%M:%S%z')"
         cp -v '/boot/grub2/grub.cfg' "/boot/grub2/grub.cfg.ansible_backup_${timestamp}"
         if grub2-mkconfig --help | grep update-bls-cmdline 1>/dev/null; then
             # For newer grub2-mkconfig on EL >= 9.x
             grub2-mkconfig --update-bls-cmdline -o '/boot/grub2/grub.cfg'
         else
             # For older grub2-mkconfig on EL <= 8.x
             grub2-mkconfig -o '/boot/grub2/grub.cfg'
         fi
  args:
    executable: '/bin/bash'
  changed_when: true
  become: true
  listen: rebuild_grub_config_by_interfaces_role

- name: Reboot to activate updated GRUB config.
  ansible.builtin.reboot:
    msg: 'Reboot initiated by Ansible "interfaces" role from League of Robots playbook/repo.'
  become: true
  listen: reboot_to_activate_changed_network_config
#
# Restart before reload: a reload after a restart may be redundant but should not fail,
# but the other way around may fail when the impact of changes was too large for a reload.
#
- name: Restart network.service
  ansible.builtin.systemd:
    name: network.service
    state: restarted
  become: true
  listen: network_restart

- name: Restart fix_network_interface_names.service
  ansible.builtin.systemd:
    name: fix_network_interface_names.service
    state: restarted
  become: true
  listen: fix_network_interface_names_restart

- name: Restart NetworkManager.service
  ansible.builtin.systemd:
    name: NetworkManager.service
    state: restarted
  become: true
  listen: NetworkManager_restart

- name: Restart nmstate.service
  ansible.builtin.systemd:
    name: nmstate.service
    state: restarted
  become: true
  listen: nmstate_restart
...
