---
- hosts: buildserver
  become: true
  tasks:
    - name: install the 'Development tools' package group
      yum:
        name: "{{ item }}"
      with_items:
        - "@Development tools"
        - libselinux-devel
        - kernel-devel

    - name: install dependencies for slurm.
      yum:
        name: "{{ item }}"
      with_items:
        - blcr
        - blcr-devel
        - hdf5-devel
        - hwloc-devel
        - lua-devel
        - man2html
        - mariadb-devel
        - munge-devel
        - munge-libs
        - mysql-devel
        - ncurses-devel
        - nss-softokn-freebl
        - numactl-devel
        - openssl-devel
        - pam-devel
        - perl
        - pkgconfig
        - readline-devel


    - name: Set lustre client source url.
      set_fact:
        lustre_rpm_url: https://downloads.whamcloud.com/public/lustre/lustre-2.10.4/el7/client/SRPMS
        lustre_src_rpm_name: lustre-2.10.4-1.src.rpm
        lustre_client_rpm_name: lustre-client-2.10.4-1.el7.x86_64.rpm

    - name: check if the buildserver has already built the client.
      stat:
        path: /root/rpmbuild/RPMS/x86_64/{{ lustre_client_rpm_name }}
      register: remote_file

    - name: build the lustre client.
      block:
        - name: Fetch the lustre client source
          get_url:
            url: "{{ lustre_rpm_url }}/{{ lustre_src_rpm_name }}"
            dest: /tmp/{{ lustre_src_rpm_name }}

        - name: build the lustre client.
          command: rpmbuild --rebuild --without servers /tmp/{{ lustre_src_rpm_name }}
          become: true
      when: remote_file.stat.exists == false

    - name: Mount isilon apps
      mount:
        path: /apps
        src: gcc-storage001.stor.hpc.local:/ifs/rekencluster/umcgst10/.envsync/tmp01
        fstype: nfs
        opts: defaults,_netdev,nolock,vers=4.0,noatime,nodiratime
        state: present
