---
- import_playbook: hpc-cloud/common.yml
- import_playbook: hpc-cloud/rabbitmq.yml
- import_playbook: hpc-cloud/memcached.yml
- import_playbook: hpc-cloud/mariadb.yml
- import_playbook: hpc-cloud/keystone.yml
- import_playbook: hpc-cloud/glance-controller.yml
- import_playbook: hpc-cloud/nova-controller.yml
- import_playbook: hpc-cloud/neutron-controller.yml
- import_playbook: hpc-cloud/cinder-controller.yml
- import_playbook: hpc-cloud/cinder-storage.yml
- import_playbook: hpc-cloud/nova-compute.yml
- import_playbook: hpc-cloud/horizon.yml
- import_playbook: hpc-cloud/heat.yml
- import_playbook: hpc-cloud/post-install.yml
...
