---
stack_prefix: 'db'
stack_domain: 'donbot'
stack_name: "{{ stack_domain }}_azure"  # stack_name must match the name of the folder that contains this vars.yml file.
os_distribution: 'rocky9'
repo_manager: 'none'
#
# Configure limited subset of repos.
# Listing the repo ID here does not mean the repo will be enabled!
# It means the repo config as listed in the yum_repos variable from
#     group_vars/all/repos.yml
# will be applied to the machine, which can include instructions for both enabling or disabling a repo.
#
yum_repos_deployed_on_clients:
  alma9: "{{ yum_repos['alma9']
              | selectattr('tags', 'defined')
              | selectattr('tags', 'intersect', ['core', 'epel', 'rsyslog', 'ltb', 'perun'])
              | map(attribute='id') }}"
  rocky9: "{{ yum_repos['rocky9']
              | selectattr('tags', 'defined')
              | selectattr('tags', 'intersect', ['core', 'epel', 'security', 'rsyslog', 'ltb', 'perun'])
              | map(attribute='id') }}"
azure_networks:
  - name: "{{ stack_prefix }}_internal_management"
    cidr: '10.10.1.0/24'
    create: true
azure_image:
  rocky9:
    offer: 'rockylinux-x86_64'
    publisher: 'resf'
    sku: '9-base'
    version: 'latest'
azure_resource_group: "{{ stack_name }}"
nameservers: [
  '8.8.4.4',  # Google DNS.
  '8.8.8.8',  # Google DNS.
]
local_admin_groups:
  - 'admin'
local_admin_users:
  - 'gerben'
  - 'marieke'
  - 'morris'
  - 'pieter'
  - 'sandi'
use_ldap: false
create_ldap: false
use_sssd: true
#
# Jumphosts from other stack-name infra groups.
# We will restrict SSH login on port 22 to these jumphosts using OpenStack security rules.
#
external_jumphosts:
  - group: talos_cluster
    hosts:
      - hostname: reception
        network: vlan16
  - group: hyperchicken_cluster
    hosts:
      - hostname: portal
        network: public
  - group: fender_cluster
    hosts:
      - hostname: corridor
        network: public
  - group: nibbler_cluster
    hosts:
      - hostname: tunnel
        network: vlan16
  - group: vaxtron_cluster
    hosts:
      - hostname: foyer
        network: external
  - group: wingedhelix_cluster
    hosts:
      - hostname: wh-porch
        network: vlan16
  - group: betabarrel_cluster
    hosts:
      - hostname: bb-porch
        network: vlan16
  - group: copperfist_cluster
    hosts:
      - hostname: cf-porch
        network: external
  - group: logs_library
    hosts:
      - hostname: hatch
        network: logs_external_public
...
