---
- name: Import pre deploy checks.
  ansible.builtin.import_playbook: pre_deploy_checks.yml

- name: Import initialization playbook for all hosts.
  ansible.builtin.import_playbook: init.yml

- name: '###==-> Roles only for completely managed chaperones. <-==###'
  hosts: chaperone,!mit_chaperone
  roles:
    - interfaces
    - iptables
    - grub
    - swap
    - logrotate
    - remove
    - update
    - logins
    - role: sssd
      when: use_sssd | default(false) | bool
    - sshd
    - basic_security
    - figlet_motd
    - resolver
    - coredumps

- name: '###==-> More Roles only for completely managed chaperones. <-==###'
  hosts:
    - chaperone,!mit_chaperone
  #
  # Use hard coded strategy linear to disable mitogen when present,
  # because mitogen fails to detect the ansible_python_interpreter correctly
  # when using delegate_to, which is used in the logs_client role.
  # There is no problem when the inventory_host for which a task is executed
  # has the same Python as the host to which the task is delegated.
  # But if the inventory_host's Python is missing on the delegate_to host,
  # then the task will fail.
  #
  strategy: linear
  roles:
    - role: logs_client
      when: ((rsyslog_external_servers is defined and ( rsyslog_external_servers|length>0 )) or ( cluster_class is defined ))
            and ( ansible_facts['os_family'] == "RedHat" )

- name: '###==-> Roles for all chaperones. <-==###'
  hosts: chaperone
  roles:
    - ssh  # client
    - locale
    - cluster
    - regular_users
    - sudoers
    - role: local_storage
      when: local_mounts is defined and local_mounts | length > 0
    - shared_storage
    - build_environment
    - envsync
    - parallax

- name: '###==-> Roles only for partially managed chaperones. <-==###'
  hosts: mit_chaperone
  roles:
    - logs_toprm
    - ogm
...
