---
- name: Import pre deploy checks.
  ansible.builtin.import_playbook: pre_deploy_checks.yml

- name: Import initialization playbook for all hosts.
  ansible.builtin.import_playbook: init.yml

- name: '###==-> Basic roles for all cluster machines part 1. <-==###'
  hosts:
    - cluster
  roles:
    - role: yum_local
      when: local_yum_repository is defined
    - interfaces
    - iptables
    - ssh  # client
    - grub
    - swap
    - locale
    - logrotate
    - remove
    - update
    - logins
    - figlet_motd
    #
    # Disabled monitoring: needs update. See also:
    # https://github.com/rug-cit-hpc/league-of-robots/issues/294
    #
    # - node_exporter
    - cluster
    - gpu  # Needs to run after 'cluster' role.
    - resolver
    - coredumps
    - role: perc_cli
      when: perc_devices is defined and perc_devices
    - role: local_storage
      when: local_mounts is defined and local_mounts | length > 0

- name: '###==-> More basic roles for all cluster machines part 1. <-==###'
  hosts:
    - cluster
  #
  # Use hard coded strategy linear to disable mitogen when present,
  # because mitogen fails to detect the ansible_python_interpreter correctly
  # when using delegate_to, which is used in the logs_client role.
  # There is no problem when the inventory_host for which a task is executed
  # has the same Python as the host to which the task is delegated.
  # But if the inventory_host's Python is missing on the delegate_to host,
  # then the task will fail.
  #
  strategy: linear
  roles:
    - role: logs_client
      when: ((rsyslog_external_servers is defined and ( rsyslog_external_servers|length>0 )) or ( cluster_class is defined ))
            and ( ansible_facts['os_family'] == "RedHat" )
...
