---
- name: Initialization roles for most hosts.
  hosts:
    - jumphost
    - repo
    - cluster
    - chaperone
    - irods
    - ldap_server
    - logs
    - data_transfer
    - jenkins
    - silo_server
  roles:
    - role: static_hostname_lookup

- name: Initialization roles for most hosts.
  hosts: all,!controller_api,!mit_chaperone
  roles:
    #
    # Either pulp_client or yum_repos must be deployed first
    # before any other role that installs/updates RPMs.
    # Note: Static host names in /etc/hosts are required for Pulp clients to resolve the Pulp server.
    #
    - role: pulp_client
      when: repo_manager == 'pulp'
    - role: yum_repos
      when: repo_manager == 'none' or
            repo_manager == 'repo_server'
    - ssh_host_signer # update in the tasks needs this role after the repo
    - admin_users
...
