---
slurm_cluster_name: 'talos'
stack_domain: 'hpc.rug.nl'
stack_name: "{{ slurm_cluster_name }}_cluster"  # stack_name must match the name of the folder that contains this vars.yml file.
stack_prefix: 'tl'
slurm_version: '22.05.2-1.el7.umcg'
slurm_allow_jobs_to_span_nodes: true
slurm_partitions:
  - name: regular  # Must be in sync with group listed in Ansible inventory.
    default: yes
    nodes: "{{ stack_prefix }}-vcompute[01-03]"  # Must be in sync with Ansible hostnames listed in inventory.
    max_nodes_per_job: "{% if slurm_allow_jobs_to_span_nodes is defined and slurm_allow_jobs_to_span_nodes is true %}{{ groups['regular']|list|length }}{% else %}1{% endif %}"
    max_cores_per_node: "{{ groups['regular'] | map('extract', hostvars, 'slurm_max_cpus_per_node') | first }}"
    max_mem_per_node: "{{ groups['regular'] | map('extract', hostvars, 'slurm_max_mem_per_node') | first }}"
    local_disk: "{{ groups['regular'] | map('extract', hostvars, 'slurm_local_disk') | first | default(0, true) }}"
    features: "{{ groups['regular'] | map('extract', hostvars, 'slurm_features') | first | default('none') }}"
    extra_options: 'TRESBillingWeights="CPU=1.0,Mem=0.5G" DenyQos=ds-short,ds-medium,ds-long'
  - name: user_interface  # Must be in sync with group listed in Ansible inventory.
    default: no
    nodes: "{{ slurm_cluster_name }}"  # Must be in sync with Ansible hostnames listed in inventory.
    max_nodes_per_job: 1
    max_cores_per_node: 1
    max_mem_per_node: 1024
    local_disk: "{{ groups['user_interface'] | map('extract', hostvars, 'slurm_local_disk') | first | default(0, true) }}"
    features: "{{ groups['user_interface'] | map('extract', hostvars, 'slurm_features') | first | default('none') }}"
    extra_options: 'TRESBillingWeights="CPU=1.0,Mem=1.0G" AllowQos=ds-short,ds-medium,ds-long'
repo_manager: 'pulp'
os_distribution: 'centos7'
figlet_font: 'ogre'
motd: |
      =========================================================
      !!! WARNING: {{ slurm_cluster_name | capitalize }} is in beta testing
      =========================================================
          This cluster may be redeployed from scratch, which
          may result in complete data loss of home dirs 
          and tmp0* group folders: You have been warned!!!
          This does not affect prm0* group folders,
          which are on a different (production) storage system.
      =========================================================
additional_etc_hosts:
  - group: docs_library
    nodes:
      - name: docs-on-bateleur
        network: external
  - group: donbot_azure
    nodes:
      - name: ladap
        network: donbot_external_network
#
# Remote logging settings - for diagnostics servers
#
logs_class: 'development'

ssh_host_signer_ca_private_key: "{{ ssh_host_signer_ca_keypair_dir }}/umcg-hpc-development-ca"
use_ldap: true
create_ldap: false
use_sssd: true
ldap_domains:
  idvault:
    uri: ldaps://172.23.40.249
    base: ou=umcg,o=asds
    schema: rfc2307
    min_id: 50100000
    max_id: 55999999
    user_object_class: posixAccount
    user_name: uid
    user_ssh_public_key: sshPublicKey
    user_member_of: groupMembership
    user_expiration_date: loginExpirationTime
    group_member: memberUid
    group_object_class: groupofnames
    #
    # LDAP is case insensitive, but we use lowercase only for quota field names,
    # so we can use simple literal strings in comparisons as opposed to regexes
    # to handle differences in UPPERCASE vs. lowercase.
    #
    # The UPPERCASE "LFS" in {{ ldap_domains[domain]['group_quota_*_limit_template'] }} Ansible variables
    # is a required placeholder that will get replaced with the value of the Logical File System (LFS)
    # for which we will try to fetch quota limits from the LDAP.
    # E.g. with
    #     group_quota_soft_limit_template: 'ruggroupumcgquotaLFSsoft'
    # the fieldname/key used to lookup the soft quota limit for the prm01 LFS is
    #     ruggroupumcgquotaprm01soft
    #
    group_quota_soft_limit_template: ruggroupumcgquotaLFSsoft
    group_quota_hard_limit_template: ruggroupumcgquotaLFS
    # listserv_mailinglist: Be careful not to use a production mailinglist for testing!
stack_networks:
  - name: vlan983
    router_network: vlan16
    type: management
    external: true
  - name: vlan985
    type: storage
    external: true
nameservers: [
  '/gcc-storage001.stor.hpc.local/172.23.40.244',  # Local DNS lookups for shared storage.
  '8.8.4.4',  # Google DNS.
  '8.8.8.8',  # Google DNS.
]
local_admin_groups:
  - 'admin'
  - 'docker'
local_admin_users:
  - 'alex2'
  - 'egon'
  - 'ger'
  - 'gerben'
  - 'henkjan'
  - 'kim'
  - 'marieke'
  - 'marloes'
  - 'max'
  - 'morris'
  - 'pieter'
  - 'robin'
  - 'sandi'
  - 'wim'
  - 'wouter'
data_transfer_only_group: 'umcg-sftp-only'
envsync_user: 'umcg-envsync'
envsync_group: 'umcg-depad'
functional_admin_group: 'umcg-funad'
hpc_env_prefix: '/apps'
regular_groups:
  - "{{ data_transfer_only_group }}"
  - "{{ envsync_group }}"
  - "{{ functional_admin_group }}"
  - 'umcg-atd'
  - 'umcg-endocrinology'
  - 'umcg-gcc'
  - 'umcg-gsad'
  - 'umcg-lifelines'
  - 'umcg-sysops'
regular_users:
  - user: "{{ envsync_user }}"
    groups: ["{{ envsync_group }}"]
  - user: 'umcg-atd-ateambot'
    groups: ['umcg-atd']
  - user: 'umcg-atd-dm'
    groups: ['umcg-atd']
  - user: 'umcg-endocrinology-dm'
    groups: ['umcg-endocrinology']
  - user: 'umcg-gcc-dm'
    groups: ['umcg-gcc']
  - user: 'umcg-gsad-ateambot'
    groups: ['umcg-gsad']
  - user: 'umcg-gsad-dm'
    groups: ['umcg-gsad']
  - user: 'umcg-lifelines-dm'
    groups: ['umcg-lifelines']
  - user: 'umcg-sysops-dm'
    groups: ['umcg-sysops']
sudoers:
  - who: ['%umcg-atd']
    become: 'umcg-atd-dm'
  - who: ['%umcg-atd']
    become: 'umcg-atd-ateambot'
  - who: ['%umcg-endocrinology-dms']
    become: 'umcg-endocrinology-dm'
  - who: ['%umcg-gcc']
    become: 'umcg-gcc-dm'
  - who: ['%umcg-gsad']
    become: 'umcg-gsad-ateambot'
  - who: ['%umcg-gsad']
    become: 'umcg-gsad-dm'
  - who: ['%umcg-lifelines-dms']
    become: 'umcg-lifelines-dm'
  - who: ['%umcg-sysops']
    become: 'umcg-sysops-dm'

#
# Shared storage related variables
#
pfs_mounts:
  - pfs: umcgst11
    source: 'gcc-storage001.stor.hpc.local:/ifs/rekencluster'
    type: nfs4
    rw_options: 'defaults,_netdev,vers=4.0,noatime,nodiratime'
    ro_options: 'defaults,_netdev,vers=4.0,noatime,nodiratime,ro'
    machines: "{{ groups['sys_admin_interface'] }}"
lfs_mounts:
  - lfs: home
    pfs: umcgst11
    rw_machines: "{{ groups['cluster'] }}"
  - lfs: tmp08
    pfs: umcgst11
    groups:
      - name: umcg-atd
      - name: umcg-endocrinology
      - name: umcg-gcc
      - name: umcg-gsad  
      - name: umcg-lifelines
        mode: '2750'
      - name: umcg-sysops
    rw_machines: "{{ groups['user_interface'] + groups['deploy_admin_interface'] + groups['compute_node'] }}"
  - lfs: rsc08
    pfs: umcgst11
    groups:
      - name: umcg-atd
      - name: umcg-gsad  
      - name: umcg-lifelines
      - name: umcg-sysops
    ro_machines: "{{ groups['compute_node'] }}"
    rw_machines: "{{ groups['user_interface'] }}"
  - lfs: prm08
    pfs: umcgst11
    groups:
      - name: umcg-atd
      - name: umcg-gcc
      - name: umcg-gsad  
      - name: umcg-lifelines
      - name: umcg-solve-rd
      - name: umcg-sysops
    rw_machines: "{{ groups['user_interface'] }}"
  - lfs: env08
    pfs: umcgst11
    ro_machines: "{{ groups['compute_node'] + groups['user_interface'] }}"
    rw_machines: "{{ groups['deploy_admin_interface'] }}"
ega_fuse_client_mounts:
  solve_rd: '/groups/umcg-solve-rd/prm08/ega-fuse-client'
ega_fuse_client_java_home: '/etc/alternatives/jre_11_openjdk'
...
