---
- name: Create a mount point directory.
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: '0550'        # protect (as much as possible) from accidental writing into this folder
    owner: root
    group: root
    # attributes: +i    # man chattr / prevent from anyone to write to this disk
    force: false
  when:
    - ansible_mounts | selectattr('mount', 'equalto', item.path) | list | length == 0
    - inventory_hostname in item.hostname | default([])
  with_items: "{{ soft_partitions }}"
  become: true

- name: Create a disk image file
  community.general.filesize:
    path: "{{ item.src }}"
    size: "{{ item.size }}G"
    mode: '0550'
    owner: root
    group: root
    force: false
    sparse: true    # speedup: most modern file systems (ones we use xfs, btrfs, ext4 ...) support sparse files
  with_items: "{{ soft_partitions }}"
  when:
    - ansible_mounts | selectattr('mount', 'equalto', item.path) | list | length == 0
    - inventory_hostname in item.hostname | default([])
  become: true

- name: Create filesystem on the disk image
  community.general.filesystem:
    force: false        # prevent formatting the existing filesystem!
    fstype: "{{ item.fstype }}"
    dev: "{{ item.src }}"
    opts: "{{ item.fsopts }}"
  with_items: "{{ soft_partitions }}"
  when:
    - ansible_mounts | selectattr('mount', 'equalto', item.path) | list | length == 0
    - inventory_hostname in item.hostname | default([])
  become: true

- name: Mount a loop volume from disk image
  ansible.posix.mount:
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    opts: loop
    state: mounted
    fstype: "{{ item.fstype }}"
  with_items: "{{ soft_partitions }}"
  when:
    - ansible_mounts | selectattr('mount', 'equalto', item.path) | list | length == 0
    - inventory_hostname in item.hostname | default([])
  become: true

- name: Refresh the host facts
  ansible.builtin.gather_facts:
  when: soft_partitions | selectattr('hostname', 'equalto', inventory_hostname) | list | length > 0

- name: Set the mount point directory permissions, user and group ownership
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: "{{ item.user }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    force: false        # don't change if not needed
  with_items: "{{ soft_partitions }}"
  when:
    - ansible_mounts | selectattr('mount', 'equalto', item.path) | list | length == 1
    - inventory_hostname in item.hostname | default([])
  become: true
...
