---
- name: 'Install dnf versionlock command.'
  ansible.builtin.package:
    name: 'dnf-command(versionlock)'
    state: latest
    update_cache: true
  become: true

- name: 'Enable automatic updates on EL >= 8.'
  ansible.builtin.import_tasks:
    file: auto_update_el8.yml
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution_major_version'] >= "8"
    - autoupdate_enabled | default(true) | bool

#
# These packages are version locked using their corresponding roles and we don't want to change that.
#
- name: 'Update all installed packages (except Slurm and iRODS) now.'
  ansible.builtin.package:
    name: '*'
    state: latest
    update_cache: true
    exclude: 'slurm*,irods*'
  become: true

- name: 'Check if we need to reboot now.'
  ansible.builtin.command:
    cmd: dnf needs-restarting -r
  register: reboot_required
  changed_when: reboot_required.rc == 1
  failed_when: reboot_required.rc >= 2
  become: true

- name: 'Reboot now (triggered by updates).'
  ansible.builtin.reboot:
    msg: Reboot initiated by Ansible role "update" from League of Robots playbook/repo.
  become: true
  when: reboot_required.rc == 1
...
