---
lfs_quota:
  prm02:
    quota_pid_increment: 0  # Value added to GID to create unique PID for a group on the PFS hosting this LFS.
    quota_limits:  # All values in GB.
      umcg-atd: 1024
      umcg-biogen: 8192
      umcg-bios: 1024
      umcg-blister: 1024
      umcg-dag3: 1024
      umcg-datateam: 1024
      umcg-erdera: 2048
      umcg-fg: 2048
      umcg-franke-scrna: 4096
      umcg-fu: 2048
      umcg-gap: 1024
      umcg-gastrocol: 5120
      umcg-gcc: 27648
      umcg-gdi: 1024
      umcg-gdio: 11264
      umcg-gonl: 5120
      umcg-griac: 9216
      umcg-grip: 2048
      umcg-gsad: 1024
      umcg-hematology: 5120
      umcg-hlhs: 3072
      umcg-immunogenetics: 10240
      umcg-integralezorg: 1024
      umcg-lifelines: 28672
      umcg-lld: 15360
      umcg-llnext: 10240
      umcg-mic: 2048
      umcg-micompany: 512
      umcg-mmbimg: 1024
      umcg-monitor-connect: 1024
      umcg-msb: 1024
      umcg-muhas: 1024
      umcg-nawijn: 2048
      umcg-pmb: 2048
      umcg-rad: 1024
      umcg-rehabilitation: 1024
      umcg-reki: 1024
      umcg-respire: 1024
      umcg-sommer: 2048
      umcg-sysops: 1024
      umcg-tifn: 6144
      umcg-ugli: 2048
      umcg-verbeek: 1024
      umcg-vdakker: 1024
      umcg-weersma: 40960
  prm03:
    quota_pid_increment: 200000  # Value added to GID to create unique PID for a group on the PFS hosting this LFS.
    quota_limits:  # All values in GB.
      umcg-atd: 1024
      umcg-biogen: 17408
      umcg-bionic-mdd-gwama: 13312
      umcg-dag3: 3072
      umcg-datateam: 1024
      umcg-endocrinology: 1024
      umcg-fg: 4096
      umcg-forcespe: 1024
      umcg-franke-scrna: 20480
      umcg-fu: 2048
      umcg-gap: 1024
      umcg-gastrocol: 5120
      umcg-gcc: 1024
      umcg-gdi: 4096
      umcg-gdio: 12288
      umcg-gonl: 10240
      umcg-griac: 13312
      umcg-grip: 2048
      umcg-gsad: 1024
      umcg-hematology: 5120
      umcg-hgsvc: 1024
      umcg-hlhs: 3072
      umcg-immunogenetics: 4096
      umcg-impact: 3072
      umcg-intercept: 2048
      umcg-lifelines: 17408
      umcg-lld: 3072
      umcg-llnext: 18432
      umcg-mic: 2048
      umcg-micompany: 512
      umcg-muhas: 1024
      umcg-nawijn: 2048
      umcg-neonatology: 6144
      umcg-nephrology: 3072
      umcg-pgx: 1024
      umcg-pmb: 5120
      umcg-radicon: 5120
      umcg-sysops: 1024
      umcg-tifn: 5120
      umcg-ucu: 1024
      umcg-ugli: 6144
      umcg-vdakker: 1024
      umcg-weersma: 8192
  prm08:
    quota_limits:  # All values in GB.
      umcg-atd: 512
      umcg-gcc: 128
      umcg-gsad: 512
      umcg-sysops: 128
  prm09:
    quota_limits:  # All values in GB.
      umcg-atd: 512  
      umcg-gcc: 128
      umcg-gsad: 512
      umcg-sysops: 128
  rsc01:
    quota_limits:  # All values in GB.
  rsc02:
    quota_pid_increment: 500000  # Value added to GID to create unique PID for a group on the PFS hosting this LFS.
    quota_limits:  # All values in GB.
      umcg-atd: 1024
      umcg-fg: 1024
      umcg-gcc: 3072
      umcg-gdio: 1024
      umcg-grip: 1024
      umcg-hlhs: 1024
      umcg-lifelines: 41984
      umcg-sysops: 1024
      umcg-ucu: 5120
  rsc04:
    quota_limits:  # All values in GB.
      umcg-atd: 1024
      #umcg-biogen: value not approved yet.
      umcg-erdera: 2048
      umcg-fg: 1024
      umcg-gcc: 1024
      umcg-gdio: 1024
      umcg-grip: 1024
      umcg-hlhs: 1024
      umcg-lifelines: 40960
  rsc08:
    quota_limits:  # All values in GB.
      umcg-atd: 512
      umcg-gcc: 128
      umcg-gsad: 512
      umcg-sysops: 128
  tmp01:
    quota_limits:  # All values in GB.
  tmp02:
    quota_pid_increment: 0  # Value added to GID to create unique PID for a group on the PFS hosting this LFS.
    quota_limits:  # All values in GB.
      umcg-as: 1024
      umcg-atd: 1024
      umcg-biogen: 20480
      umcg-bionic-mdd-gwama: 1024
      umcg-bios: 1024
      umcg-dag3: 1024
      umcg-datateam: 1024
      umcg-endocrinology: 5120
      umcg-fg: 10240
      umcg-franke-scrna: 20480
      umcg-fu: 2048
      umcg-gap: 1024
      umcg-gastrocol: 10240
      umcg-gcc: 9216
      umcg-gdi: 1024
      umcg-gdio: 14336
      umcg-gonl: 3072
      umcg-griac: 20480
      umcg-grip: 1024
      umcg-gsad: 1024
      umcg-hematology: 3072
      umcg-hgsvc: 2048
      umcg-hlhs: 1024
      umcg-immunogenetics: 2048
      umcg-impact: 1024
      umcg-intercept: 2048
      umcg-lifelines: 92160
      umcg-lld: 1024
      umcg-llnext: 2048
      umcg-mic: 2048
      umcg-micompany: 512
      umcg-mmbimg: 1024
      umcg-monitor-connect: 1024
      umcg-msb: 1024
      umcg-muhas: 1024
      umcg-nawijn: 4096
      umcg-neonatology: 6144
      umcg-nephrology: 3072
      umcg-pgx: 1024
      umcg-pmb: 8192
      umcg-rad: 1024
      umcg-radicon: 1024
      umcg-rehabilitation: 1024
      umcg-reki: 1024
      umcg-sommer: 2048
      umcg-sysops: 1024
      umcg-tifn: 2048
      umcg-ucu: 3072
      umcg-ugli: 1024
      umcg-verbeek: 1024
      umcg-vdakker: 1024
      umcg-visclasataxia: 1024
      umcg-weersma: 11264
  tmp04:
    quota_pid_increment: 300000  # Value added to GID to create unique PID for a group on the PFS hosting this LFS.
    quota_limits:  # All values in GB.
      umcg-as: 1024
      umcg-atd: 5120
      umcg-biogen: 63488
      umcg-bionic-mdd-gwama: 1024
      umcg-bios: 4096
      umcg-blister: 1024
      umcg-dag3: 1024
      umcg-datateam: 1024
      umcg-endocrinology: 2048
      umcg-erdera: 11264
      umcg-fg: 10240
      umcg-forcespe: 1024
      umcg-franke-scrna: 15360
      umcg-fu: 2048
      umcg-gap: 1024
      umcg-gastrocol: 10240
      umcg-gcc: 9216
      umcg-gdi: 2048
      umcg-gdio: 8192
      umcg-gonl: 1024
      umcg-griac: 2048
      umcg-grip: 1024
      umcg-gsad: 1024
      umcg-hematology: 3072
      umcg-hlhs: 5120
      umcg-immunogenetics: 2048
      umcg-impact: 1024
      umcg-integralezorg: 1024
      umcg-lifelines: 40960
      umcg-lld: 8192
      umcg-llnext: 2048
      umcg-mic: 2048
      umcg-micompany: 1024
      umcg-nawijn: 4096
      umcg-neonatology: 3072
      umcg-nephrology: 1024
      umcg-path-bioinformatica: 1024
      umcg-pgx: 1024
      umcg-pmb: 1024
      umcg-rehabilitation: 1024
      umcg-respire: 1024
      umcg-sysops: 1024
      umcg-tifn: 2048
      umcg-ugli: 1024
      umcg-vdakker: 1024
      umcg-verbeek: 1024
      umcg-weersma: 10240
  tmp08:
    quota_limits:  # All values in GB.
      umcg-atd: 512
      umcg-gcc: 128
      umcg-gsad: 512
      umcg-gst: 512
      umcg-sysops: 128
      umcg-vipt: 512
  tmp09:
    quota_limits:  # All values in GB.
      umcg-atd: 512    
      umcg-gcc: 128
      umcg-gsad: 512  
      umcg-gst: 512      
      umcg-sysops: 128
      umcg-vipt: 512
...
