---
#
## Repo servers global variables
#
repo_servers_certificate: 'logs_library/logs_development.pem'
repo_servers_certificate_key: 'logs_library/logs_development.key'
repo_servers:
  - name: repo-primary
  - name: repo-secondary
#
# Pulp repos.
#
pulp_repos:
  alma9:
    - name: baseos
      description: 'AlmaLinux 9 - BaseOS.'
      remote_url: https://repo.almalinux.org/almalinux/9/BaseOS/x86_64/os/
      acs:
        - name: "9{{ os_minorversion }}"
          remote_url: "https://repo.almalinux.org/almalinux/9{{ os_minorversion }}/BaseOS/x86_64/os/"
    - name: appstream
      description: 'AlmaLinux 9 - AppStream.'
      remote_url: https://repo.almalinux.org/almalinux/9/AppStream/x86_64/os/
      acs:
        - name: "9{{ os_minorversion }}"
          remote_url: "https://repo.almalinux.org/almalinux/9{{ os_minorversion }}/AppStream/x86_64/os/"
    - name: crb
      description: 'AlmaLinux 9 - CRB.'
      remote_url: https://repo.almalinux.org/almalinux/9/CRB/x86_64/os/
      acs:
        - name: "9{{ os_minorversion }}"
          remote_url: "https://repo.almalinux.org/almalinux/9{{ os_minorversion }}/CRB/x86_64/os/"
    - name: extras
      description: 'AlmaLinux 9 - Extras.'
      remote_url: https://repo.almalinux.org/almalinux/9/extras/x86_64/os/
      acs:
        - name: "9{{ os_minorversion }}"
          remote_url: "https://repo.almalinux.org/almalinux/9{{ os_minorversion }}/extras/x86_64/os/"
    - name: epel
      description: 'Extra Packages for Enterprise Linux 9 (EPEL).'
      remote_url: https://download.fedoraproject.org/pub/epel/9/Everything/x86_64
    - name: cpel
      description: 'UMCG Custom Packages for Enterprise Linux 9 (CPEL).'
      #remote_url: no remote for our homebrew packages.
    - name: ltb
      description: 'LTB (LDAP Tool Box) project OpenLDAP packages for Enterprise Linux 9.'
      remote_url: https://ltb-project.org/rpm/openldap25/9/x86_64/
    - name: rsyslog
      description: 'rsyslog v8 (from Adiscon) for EPEL 9.'
      remote_url: https://rpms.adiscon.com/v8-stable/epel-9/x86_64/
    - name: e2fsprogs  # Dependency for Lustre project quota.
      description: 'Ext filesystem utility releases for Enterprise Linux 9.'
      remote_url: https://downloads.whamcloud.com/public/e2fsprogs/latest/el9/
    #
    # Lustre packages still broken and cannot be installed on EL 9.x due to silly Python 2 dependency resulting in:
    # "nothing provides /usr/bin/python2 needed by lustre-client-dkms-2.15.4-1.el9.noarch from lustre"
    #
    #- name: lustre
    #  description: 'Lustre client leatest releases for Enterprise Linux 9.3.'
    #  # WARNING: There is no LTS release link for el9 yet.
    #  # WARNING: When el9.4 is released the link below for el9.3 will not get updated automatically!
    #  remote_url: https://downloads.whamcloud.com/public/lustre/latest-release/el9.3/client/
    - name: irods
      description: 'RENCI iRODS for Enterprise Linux 9.'
      remote_url: https://packages.irods.org/yum/pool/el9/x86_64/
    - name: cvmfs
      description: 'CernVM-FS repo'
      remote_url: https://cvmrepo.web.cern.ch/cvmrepo/yum/cvmfs/EL/9/x86_64/
  rocky9:
    - name: baseos
      description: 'Rocky Linux 9 - BaseOS.'
      remote_url: https://mirrors.rockylinux.org/mirrorlist?arch=x86_64&repo=BaseOS-9
      acs:
        - name: vault
          remote_url: "https://dl.rockylinux.org/vault/rocky/9{{ os_minorversion }}/BaseOS/x86_64/os/"
    - name: appstream
      description: 'Rocky Linux 9 - AppStream.'
      remote_url: https://mirrors.rockylinux.org/mirrorlist?arch=x86_64&repo=AppStream-9
      acs:
        - name: vault
          remote_url: "https://dl.rockylinux.org/vault/rocky/9{{ os_minorversion }}/AppStream/x86_64/os/"
    - name: crb
      description: 'Rocky Linux 9 - CRB.'
      remote_url: https://mirrors.rockylinux.org/mirrorlist?arch=x86_64&repo=CRB-9
      acs:
        - name: vault
          remote_url: "https://dl.rockylinux.org/vault/rocky/9{{ os_minorversion }}/CRB/x86_64/os/"
    - name: extras
      description: 'Rocky Linux 9 - Extras.'
      remote_url: https://mirrors.rockylinux.org/mirrorlist?arch=x86_64&repo=extras-9
      acs:
        - name: vault
          remote_url: "https://dl.rockylinux.org/vault/rocky/9{{ os_minorversion }}/extras/x86_64/os/"
    - name: epel
      description: 'Extra Packages for Enterprise Linux 9 (EPEL).'
      remote_url: https://download.fedoraproject.org/pub/epel/9/Everything/x86_64
    - name: cpel
      description: 'UMCG Custom Packages for Enterprise Linux 9 (CPEL).'
      #remote_url: no remote for our homebrew packages.
    - name: ltb
      description: 'LTB (LDAP Tool Box) project OpenLDAP packages for Enterprise Linux 9.'
      remote_url: https://ltb-project.org/rpm/openldap25/9/x86_64/
    - name: rsyslog
      description: 'rsyslog v8 (from Adiscon) for EPEL 9.'
      remote_url: https://rpms.adiscon.com/v8-stable/epel-9/x86_64/
    - name: e2fsprogs  # Dependency for Lustre project quota.
      description: 'Ext filesystem utility releases for Enterprise Linux 9.'
      remote_url: https://downloads.whamcloud.com/public/e2fsprogs/latest/el9/
    #
    # Lustre packages still broken and cannot be installed on EL 9.x due to silly Python 2 dependency resulting in:
    # "nothing provides /usr/bin/python2 needed by lustre-client-dkms-2.15.4-1.el9.noarch from lustre"
    #
    #- name: lustre
    #  description: 'Lustre client leatest releases for Enterprise Linux 9.3.'
    #  # WARNING: There is no LTS release link for el9 yet.
    #  # WARNING: When el9.4 is released the link below for el9.3 will not get updated automatically!
    #  remote_url: https://downloads.whamcloud.com/public/lustre/latest-release/el9.3/client/
    - name: irods
      description: 'RENCI iRODS for Enterprise Linux 9.'
      remote_url: https://packages.irods.org/yum/pool/el9/x86_64/
    - name: cvmfs
      description: 'CernVM-FS repo'
      remote_url: https://cvmrepo.web.cern.ch/cvmrepo/yum/cvmfs/EL/9/x86_64/

#
# List of all repos for machines that do not use Pulp.
#
yum_repos:
  oracle8:
    - id: ol8_baseos_latest
      name: 'Oracle Linux 8 BaseOS Latest ($basearch)'
      baseurl: https://yum.oracle.com/repo/OracleLinux/OL8/baseos/latest/$basearch/
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
      gpgcheck: 1
      enabled: 1
      repo_server_download: False # _could_ be downloaded, 110 G
      tags:
        - distro
        - core
    - id: ol8_appstream
      name: 'Oracle Linux 8 Application Stream ($basearch)'
      baseurl: https://yum.oracle.com/repo/OracleLinux/OL8/appstream/$basearch/
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
      gpgcheck: 1
      enabled: 1
      repo_server_download: False # too big (and unimportant), 562 G
      tags:
        - distro
        - core
    - id: ol8_codeready_builder
      name: 'Oracle Linux 8 CodeReady Builder ($basearch) - Unsupported'
      baseurl: https://yum.oracle.com/repo/OracleLinux/OL8/codeready/builder/$basearch/
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
      gpgcheck: 1
      enabled: 1
      repo_server_download: False # too big (and unimportant), 317 G
      tags:
        - distro
        - core
    - id: ol8_MODRHCK
      name: 'Latest RHCK with fixes from Oracle for Oracle Linux $releasever ($basearch)'
      baseurl: https://yum.oracle.com/repo/OracleLinux/OL8/MODRHCK/x86_64/
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
      gpgcheck: 1
      enabled: 1
      priority: 20
      tags:
        - distro
        - core
    #
    # EPEL
    #
    - id: ol8_developer_EPEL
      name: 'Oracle Linux $releasever EPEL Packages for Development ($basearch)'
      baseurl: https://yum.oracle.com/repo/OracleLinux/OL8/developer/EPEL/$basearch/
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
      gpgcheck: 1
      enabled: 1
      repo_server_download: False # too big, would be nice to have, but not urgent, 381 GB
      tags:
        - epel
    - id: ol8_developer_EPEL_modular
      name: 'Oracle Linux $releasever EPEL Modular Packages for Development ($basearch)'
      baseurl: https://yum.oracle.com/repo/OracleLinux/OL8/developer/EPEL/modular/$basearch/
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
      gpgcheck: 1
      enabled: 1
      repo_server_download: False # unimportant, small < 1 G
      tags:
        - epel
    #
    # Kernel
    #
    - id: ol8_UEKR6
      name: 'Latest Unbreakable Enterprise Kernel Release 6 for Oracle Linux $releasever ($basearch)'
      baseurl: https://yum.oracle.com/repo/OracleLinux/OL8/UEKR6/$basearch/
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
      gpgcheck: 1
      enabled: 1
      repo_server_download: False # _could_ be downloaded, 70 G
      tags:
        - distro
        - uek
    #
    # Rsyslog
    #
    - id: rsyslog
      name: 'Rsyslog (Adiscon for x86_64)'
      baseurl: http://rpms.adiscon.com/v8-stable/epel-8/x86_64/
      enabled: 1
      repo_server_download: true # important, < 1 G
      gpgcheck: 1
      gpgkeysource: 'https://rpms.adiscon.com/RPM-GPG-KEY-Adiscon'
      tags:
        - rsyslog
  alma9:
    - id: baseos
      name: AlmaLinux 9 - BaseOS
      mirrorlist: https://mirrors.almalinux.org/mirrorlist/9/baseos
      enabled: 1
      repo_server_download: true
      gpgcheck: 1
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux-9
      tags:
        - distro
        - core
    - id: appstream
      name: Rocky Linux 9 - AppStream
      mirrorlist: https://mirrors.almalinux.org/mirrorlist/9/appstream
      enabled: 1
      repo_server_download: true
      gpgcheck: 1
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux-9
      tags:
        - distro
        - core
    - id: crb
      name: Rocky Linux 9 - CRB
      mirrorlist: https://mirrors.almalinux.org/mirrorlist/$releasever/crb
      enabled: 1
      repo_server_download: true
      gpgcheck: 1
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux-9
      tags:
        - distro
        - core
    - id: extras
      name: Rocky Linux 9 - Extras
      mirrorlist: https://mirrors.almalinux.org/mirrorlist/$releasever/extras
      enabled: 1
      repo_server_download: true
      gpgcheck: 1
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux-9
      tags:
        - distro
        - extras
    #
    # EPEL
    #
    - id: epel
      name: 'Extra Packages for Enterprise Linux 9'
      metalink: 'https://mirrors.fedoraproject.org/metalink?repo=epel-9&arch=$basearch&infra=$infra&content=$contentdir'
      enabled: 1
      repo_server_download: true
      gpgcheck: 1
      gpgkeysource: 'https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9'
      tags:
        - epel
    #
    # LTB
    #
    - id: ltb
      name: 'LTB (LDAP Tool Box) project OpenLDAP packages for Enterprise Linux 9'
      baseurl: 'https://ltb-project.org/rpm/openldap25/9/$basearch'
      enabled: 1
      repo_server_download: true
      gpgcheck: 1
      gpgkeysource: 'https://ltb-project.org/documentation/_static/RPM-GPG-KEY-LTB-PROJECT-SECURITY'
      tags:
        - ltb
    #
    # rsyslog
    #
    - id: rsyslog
      name: 'rsyslog v8 (from Adiscon) for EPEL 9'
      baseurl: 'https://rpms.adiscon.com/v8-stable/epel-9/$basearch'
      enabled: 1
      repo_server_download: true
      gpgcheck: 1
      gpgkeysource: 'https://rpms.adiscon.com/RPM-GPG-KEY-Adiscon'
      tags:
        - rsyslog
    #
    # perun
    #
    - id: perun
      name: 'Perun IdM Slave Scripts'
      baseurl: 'https://repo.cerit-sc.cz/el-perun/noarch/'
      gpgkeysource: https://repo.cerit-sc.cz/el-perun/repo.cerit-sc.cz.gpg.pub
      gpgcheck: 1
      enabled: 1
      repo_server_download: true
      tags:
        - perun
    #
    # iRODS
    #
    - id: irods
      name: 'RENCI iRODS for Enterprise Linux 9'
      baseurl: 'https://packages.irods.org/yum/pool/el9/x86_64/'
      enabled: 1
      repo_server_download: true
      gpgcheck: 0
      tags:
        - irods
    #
    # Jenkins
    #
    - id: jenkins
      name: "Jenkins{{ '-stable' if (jenkins_prefer_lts | default(true) | bool) else '' }}"
      baseurl: "https://pkg.jenkins.io/rpm{{ '-stable' if (jenkins_prefer_lts | default(true) | bool) else '' }}"
      enabled: 1
      repo_server_download: true
      gpgcheck: 1
      gpgkeysource: "https://pkg.jenkins.io/rpm{{ '-stable' if (jenkins_prefer_lts | default(true) | bool) else '' }}/repodata/repomd.xml.key"
      tags:
        - jenkins
  rocky9:
    - id: baseos
      name: Rocky Linux 9 - BaseOS
      mirrorlist: https://mirrors.rockylinux.org/mirrorlist?arch=$basearch&repo=BaseOS-9
      enabled: 1
      repo_server_download: true
      gpgcheck: 1
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-Rocky-9
      tags:
        - distro
        - core
    - id: appstream
      name: Rocky Linux 9 - AppStream
      mirrorlist: https://mirrors.rockylinux.org/mirrorlist?arch=$basearch&repo=AppStream-9
      enabled: 1
      repo_server_download: true
      gpgcheck: 1
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-Rocky-9
      tags:
        - distro
        - core
    - id: crb
      name: Rocky Linux 9 - CRB
      mirrorlist: https://mirrors.rockylinux.org/mirrorlist?arch=$basearch&repo=CRB-9
      enabled: 1
      repo_server_download: true
      gpgcheck: 1
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-Rocky-9
      tags:
        - distro
        - core
    #
    # Rocky Security
    #
    - id: rocky-release-security
      name: 'Security Special Interest Group (SIG)'
      mirrorlist: https://mirrors.rockylinux.org/mirrorlist?arch=x86_64&repo=rocky-sig-security-common-9
      enabled: 1
      repo_server_download: true
      gpgcheck: 1
      gpgkeysource: 'https://dl.rockylinux.org/pub/sig/9/security/x86_64/security-common/RPM-GPG-KEY-Rocky-SIG-Security'
      tags:
        - distro
        - security
    #
    # Rocky Extras
    #
    - id: extras
      name: Rocky Linux 9 - Extras
      mirrorlist: https://mirrors.rockylinux.org/mirrorlist?arch=$basearch&repo=extras-9
      enabled: 1
      repo_server_download: true
      gpgcheck: 1
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-Rocky-9
      tags:
        - distro
        - extras
    #
    # EPEL
    #
    - id: epel
      name: 'Extra Packages for Enterprise Linux 9 - $basearch'
      metalink: 'https://mirrors.fedoraproject.org/metalink?repo=epel-9&arch=$basearch&infra=$infra&content=$contentdir'
      enabled: 1
      repo_server_download: true
      gpgcheck: 1
      gpgkeysource: 'https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9'
      tags:
        - epel
    #
    # LTB
    #
    - id: ltb
      name: 'LTB (LDAP Tool Box) project OpenLDAP packages for Enterprise Linux 9.'
      baseurl: 'https://ltb-project.org/rpm/openldap25/9/$basearch'
      enabled: 1
      repo_server_download: true
      gpgcheck: 1
      gpgkeysource: 'https://ltb-project.org/documentation/_static/RPM-GPG-KEY-LTB-PROJECT-SECURITY'
      tags:
        - ltb
    #
    # rsyslog
    #
    - id: rsyslog
      name: 'rsyslog v8 (from Adiscon) for EPEL 9.'
      baseurl: 'https://rpms.adiscon.com/v8-stable/epel-9/$basearch'
      enabled: 1
      repo_server_download: true
      gpgcheck: 1
      gpgkeysource: 'https://rpms.adiscon.com/RPM-GPG-KEY-Adiscon'
      tags:
        - rsyslog
    #
    # perun
    #
    - id: perun
      name: 'Perun IdM Slave Scripts'
      baseurl: 'https://repo.cerit-sc.cz/el-perun/noarch/'
      gpgkeysource: 'https://repo.cerit-sc.cz/el-perun/repo.cerit-sc.cz.gpg.pub'
      gpgcheck: 1
      enabled: 1
      repo_server_download: true
      tags:
        - perun
    #
    # iRODS
    #
    - id: irods
      name: 'RENCI iRODS for Enterprise Linux 9.'
      baseurl: 'https://packages.irods.org/yum/pool/el9/x86_64/'
      enabled: 1
      repo_server_download: true
      gpgcheck: 1
      gpgkeysource: 'https://packages.irods.org/irods-signing-key.asc'
      tags:
        - irods
    #
    # Jenkins
    #
    - id: jenkins
      name: "Jenkins{{ '-stable' if (jenkins_prefer_lts | default(true) | bool) else '' }}"
      baseurl: "https://pkg.jenkins.io/redhat{{ '-stable' if (jenkins_prefer_lts | default(true) | bool) else '' }}"
      enabled: 1
      repo_server_download: true
      gpgcheck: 1
      gpgkeysource: "https://pkg.jenkins.io/redhat{{ '-stable' if (jenkins_prefer_lts | default(true) | bool) else '' }}/jenkins.io-2023.key"
      tags:
        - jenkins
#
# Default list of yum repos that will be managed by Ansible on a machine.
# The items listed here must match 'id' attributes for repos in the 'yum_repos' variable listed above.
# If you need a different (sub)set of the repos, then you can override 'yum_repos_deployed_on_clients' for a subset of machines
# either in the group_vars for the stack, the group_vars for a specific inventory group,
# the host_vars for a specific host or the static_inventory for a stack.
#
yum_repos_deployed_on_clients:
  oracle8: "{{ yum_repos['oracle8']
              | selectattr('tags', 'defined')
              | selectattr('tags', 'intersect', ['core', 'uek', 'rsyslog'])
              | map(attribute='id') }}"
  alma9: "{{ yum_repos['alma9']
              | selectattr('tags', 'defined')
              | selectattr('tags', 'intersect', ['core', 'rsyslog'])
              | map(attribute='id') }}"
  rocky9: "{{ yum_repos['rocky9']
              | selectattr('tags', 'defined')
              | selectattr('tags', 'intersect', ['core', 'security', 'rsyslog'])
              | map(attribute='id') }}"
...
