---
ssh_host_signer_ca_keypair_dir: "ssh-host-ca"
ssh_host_signer_ca_private_key: "{{ ssh_host_signer_ca_keypair_dir }}/{{ stack_name }}-ca"
ssh_host_signer_key_types: '.*(rsa|ed25519).*'
ssh_host_signer_hostnames: "{{ inventory_hostname }}\
    {% if ansible_fqdn is defined and ansible_fqdn != inventory_hostname %}\
      ,{{ ansible_fqdn }}\
    {% endif %}\
    {% for host in groups['jumphost'] | default([]) %}\
      ,{{ host }}+{{ inventory_hostname }}\
    {% endfor %}\
    {% for external_jumphost in external_jumphosts | default([])
       | map(attribute='hosts') | flatten
       | map(attribute='hostname') %}\
      ,{{ external_jumphost }}+{{ inventory_hostname }}\
    {% endfor %}"
ai_jumphost: "{{ lookup('env','AI_PROXY') }}"
#
# Local volume size (root partition) for all instances
#
local_volume_size_root: 33
#
# Public keys of all local admins.
#
public_keys_of_local_admins: "{{ local_admin_users | map('extract', auth_users) \
    | rejectattr('pub_keys', 'none') | rejectattr('pub_keys', 'undefined') \
    | map(attribute='pub_keys') \
    | map('regex_findall', '^([^\\n]+)', 'multiline=True') | flatten }}"
#
# Local group specs.
# Note:
#  * All local groups are listed here.
#  * In ../[stack_name]/vars.yml we list which groups are created locally on which stack.
#  * Never ever change nor recycle a GID value here unless you are in for a surprise...
#
auth_groups:
  admin:
    gid: 20000
  docker:
    gid: 20001
  users:
    gid: 20002
  depad:
    gid: 20003
  solve-rd:
    gid: 20004
  umcg-atd:
    gid: 20005
  funad:
    gid: 20006
  umcg-gap:
    gid: 20007
  umcg-gd:
    gid: 20008
  umcg-genomescan:
    gid: 20009
  umcg-gsad:
    gid: 20010
  umcg-gst:
    gid: 20011
  umcg-vipt:
    gid: 20012
  umcg-depad:
    gid: 20013
  umcg-funad:
    gid: 20014
  #
  # FUNctional USers group.
  # Used for all functional accounts on chaperone machines:
  #  * All functional accounts must be a member of this group.
  #  * Group is added to /etc/security/access.conf maintained by central IT dept.
  #  * Ensures (local) functional accounts can login and use cron.
  #
  umcg-funus:
    gid: 20015
  umcg-labgnkbh:
    gid: 20016
  umcg-patho:
    gid: 20017
  umcg-lab:
    gid: 20018
  vipt:
    gid: 20019
  umcg-pr:
    gid: 20020
  umcg-logstoprm:
    gid: 20021
  MEDGEN-NFG GCC Analyse Team:
    gid: 4560734
  lsaai:
    gid: 20022
  umcg-ogm:
    gid: 20023
  umcg-pgx:
    gid: 20024
#
# Default for a group of users that are only allowd to transfer data.
# Is used by the sshd role and listed in
#     roles/sshd/defaults/main.yml,
# but that file is not used when the
#     roles/sshd/templates/sshd_config
# is redeployed by other roles like the ldap or sssd roles.
# Therefore we set a default here too.
#
data_transfer_only_group: sftp-only
#
# Iptables additional configurations 
#
iptables_extras_dir: '/etc/iptables_extras.d/'
#
# Used in static_hostname_lookup, logs_client, logs_server and logs_toprm roles
#
logs_server_public_networks:
  development:
    - name: earl1
      network: vlan16
    - name: earl2
      network: logs_external_public
  diagnostics:
    - name: earl3
      network: logs_external_public
    - name: earl4
      network: vlan16
  research:
    - name: earl5
      network: vlan16
    - name: earl6
      network: logs_external_public
#
## Azure
#
azure_location: westeurope
#
## Some hosts are needed globally
#
additional_etc_hosts_for_all_stacks:
  - group: docs_library
    nodes:
      - name: docs-on-bateleur
        network: external
  - group: donbot_azure
    nodes:
      - name: ladap
        network: donbot_external_network
  - group: logs_library
    nodes:
      - name: repo-primary
        network: logs_external_public
  - group: logs_library
    nodes:
      - name: repo-secondary
        network: vlan16
...
