---
ip_addresses:
  bb-dragen:
    vlan1336:  # Manually selected IP, because machine is not controlled by OpenStack.
      address: 172.23.77.133
      netmask: /32
    vlan990:
      address: 192.168.1.61
      netmask: /32
    vlan990_ipmi:
      address: 192.168.1.241
      netmask: /32
  bb-porch:
    vlan1336:
      address: 172.23.77.51
      netmask: /32
      publicly_exposed: true  # This internal IP is linked to a public (floating) IP.
    vlan16:
      address: 195.169.22.140
      netmask: /32
      fqdn: 'NXDOMAIN'
  bb-storage:
    vlan1336:
      address: 172.23.77.63
      netmask: /32
    vlan990:
      address: 192.168.1.158
      netmask: /32
  bb-transfer:
    vlan1336:
      address: 172.23.77.84
      netmask: /32
      publicly_exposed: true  # This internal IP is linked to a public (floating) IP.
    vlan16:
      address: 195.169.22.143
      netmask: /32
      fqdn: 'bb-transfer.hpc.rug.nl'
  betabarrel:
    vlan1336:
      address: 172.23.77.111
      netmask: /32
    vlan990:
      address: 192.168.1.178
      netmask: /32
  vlan1336-vlan16-router:
    vlan1336:
      address: 172.23.77.1
      netmask: /32
    vlan16:
      address: 195.169.22.48
      netmask: /32
      fqdn: 'NXDOMAIN'
...
