---
- name: Restarting PGSQL and making sure it is enabled
  ansible.builtin.systemd:
    name: postgresql
    state: restarted
    enabled: true
  become: true
  listen: restart_postgresql

- name: Make sure iRODS service is enabled and restarted.
  ansible.builtin.sysvinit:
    name: irods
    enabled: true
    state: restarted
  become: true
  listen: irodsctl_restart
...
