---
- name: "Collect variables from {{ local_ssh_client_config_path }}."
  ansible.builtin.include_vars:
    file: "{{ local_ssh_client_config_path }}"
    name: include_ssh_client_settings_for_stack
  delegate_to: localhost
  connection: local
  run_once: true

- name: Add CA public key to list of all public CA keys.
  ansible.builtin.set_fact:
    public_certificate_authorities: "{{ public_certificate_authorities | default([]) + [include_ssh_client_settings_for_stack['ssh_client_known_hosts']] }}"
  when:
    - include_ssh_client_settings_for_stack['ssh_client_known_hosts'] is defined
    - include_ssh_client_settings_for_stack['ssh_client_known_hosts'] is not none
    - include_ssh_client_settings_for_stack['ssh_client_known_hosts'] | default('') | length >= 1
  delegate_to: localhost
  connection: local
  run_once: true

- name: "Create /etc/ssh/ssh_config.d/{{ each_stack }}.conf config file."
  ansible.builtin.template:
    src: ssh_client_config.j2
    dest: "/etc/ssh/ssh_config.d/{{ each_stack }}.LoR.conf"
    owner: root
    group: root
    mode: '0644'
  when:
    - include_ssh_client_settings_for_stack['ssh_client_jumphosts'] is defined
    - include_ssh_client_settings_for_stack['ssh_client_jumphosts'] is not none
    - include_ssh_client_settings_for_stack['ssh_client_jumphosts'] | default('') | length >= 1
  become: true
...
