---
# - name: Delete /etc/ssh/ssh_known_hosts to cleanup outdated content.
#   ansible.builtin.file:
#     path: /etc/ssh/ssh_known_hosts
#     state: absent
#   become: true

- name: Create /etc/ssh/ssh_config.d/ directory.
  ansible.builtin.file:
    path: /etc/ssh/ssh_config.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Make sure /etc/ssh/ssh_config.d/*.conf config files are included.
  ansible.builtin.lineinfile:
    dest: /etc/ssh/ssh_config
    mode: '0644'
    owner: root
    group: root
    create: false
    insertafter: EOF
    regexp: "(?i)^#?Include /etc/ssh/ssh_config.d/.*$"
    line: 'Include /etc/ssh/ssh_config.d/*.conf'
  become: true

- name: Configure ssh client for all external stacks.
  ansible.builtin.include_tasks:
    file: configure_ssh_client_for_all_stacks.yml
...
