---
#
# We only check if the envsync account for deploy admins exists; Hence we DO NOT create it here!
# Depending on wether this account comes from an LDAP or is a local account,
# it must have been created earlier on in the play.
#
- name: 'Check if envsync group is present (without creating one if not existing yet).'
  ansible.builtin.group:
    name: "{{ envsync_group }}"
    state: present
  become: false

- name: 'Check if envsync user is present (without creating one if not existing yet).'
  block:
    - name: 'Check if envsync user is present assuming all its groups are either local or from an LDAP.'
      ansible.builtin.user:
        name: "{{ envsync_user }}"
        group: "{{ envsync_user }}"
        groups: "{{ regular_users | selectattr('name', 'equalto', envsync_user) | map(attribute='groups') | flatten | unique }}"
        home: "/home/{{ envsync_user }}"
        create_home: false
        append: false
      become: false
  rescue:
    - name: 'Fallback check if envsync user and only its primary group are present.'
      #
      # This fallback option will not check for other groups.
      # Required for example when some of the secondary groups come from an LDAP while envsync_user & envsync_group are local.
      #
      ansible.builtin.user:
        name: "{{ envsync_user }}"
        group: "{{ envsync_user }}"
        home: "/home/{{ envsync_user }}"
        create_home: false
      become: false

- name: "Create {{ hpc_env_prefix }} folder in the root of the filesystem unless the machine already has a dedicated mount for {{ hpc_env_prefix }}."
  ansible.builtin.file:
    path: "{{ hpc_env_prefix }}"
    state: directory
    owner: root
    group: "{{ envsync_group }}"
    mode: '2775'
  when:
    - local_mounts | default([])
        | selectattr('mount_point', 'defined')
        | selectattr('mount_point', 'equalto', hpc_env_prefix)
        | length <= 0
    - inventory_hostname not in groups['user_interface'] | default([])  # User Interface will mount an env* LFS in /apps
    - inventory_hostname not in groups['compute_node'] | default([])  # Compute nodes will mount an env* LFS in /apps
  become: true

#
# Configure environment synchronization account.
#
- name: 'Initialize envsync account creating home dir if it did not exist yet.'
  ansible.builtin.command:
    cmd: |
         /sbin/mkhomedir_helper '{{ envsync_user }}' 0077
    creates: "/home/{{ envsync_user }}"
  become: true

- name: 'Allow passwordless sudo to the environment synchronization account for deploy admin users.'
  ansible.builtin.lineinfile:
    dest: '/etc/sudoers'
    regexp: '(\s+)ALL=\({{ envsync_user }}\)(\s+)'
    line: "%{{ envsync_group | regex_replace(' ', '\\ ') }}    ALL=({{ envsync_user }})    NOPASSWD:ALL"
    owner: root
    group: root
    mode: '0440'
  become: true

- name: 'Insert/update block into ~/.bashrc to ensure we use the correct environment for syncing.'
  ansible.builtin.blockinfile:
    dest: "/home/{{ envsync_user }}/.bashrc"
    block: |
           #
           # Non interactive processes like rsync and sftp will break
           # when anything they did not expect is printed to STDOUT or STDERR.
           # Therefore, only configure the environment when
           #   * either the shell was started with -i flag to create an interactive shell
           #   * or a non-interactive process like a cron job requested a modified environment explicitly.
           #
           if [[ "${-}" == *'i'* ]] || [[ "${SOURCE_HPC_ENV}" == 'True' ]]; then
             [[ $(id -gn) == '{{ envsync_group }}' ]] || exec newgrp '{{ envsync_group }}'
             cd
             umask 0002
             module load depad-utils
             module list
           fi
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Setup environment for environment synchronization account."
    insertafter: EOF
    create: false
  become: true

#
# Work around to prevent
#   "Error while setting attributes: /home/umcg-envsync/.ssh/id_ed25519.pub: Operation not permitted"
#   "msg: chattr failed"
# See
#   https://github.com/ansible-collections/community.crypto/issues/416
#   https://github.com/ansible/ansible/issues/77217
#
- name: 'Touch key pair files as workround for chattr bug in ansible core.'
  ansible.builtin.shell: |
      set -e
      set -u
      set -o pipefail
      if [[ ! -e "{{ envsync_key_file_path }}" ]]; then
          $(umask 0077 && touch "{{ envsync_key_file_path }}")
          echo "Touched {{ envsync_key_file_path }}"
      fi
      if [[ ! -e "{{ envsync_key_file_path }}.pub" ]]; then
          $(umask 0077 && touch "{{ envsync_key_file_path }}.pub")
          echo "Touched {{ envsync_key_file_path }}.pub"
      fi
  register: envsync_touch_key_pair
  changed_when: "'Touched' in envsync_touch_key_pair.stdout"
  become: true
  become_user: "{{ envsync_user }}"

- name: 'Create ssh key pair for rsyncing cache to compute nodes.'
  community.crypto.openssh_keypair:
    path: "{{ envsync_key_file_path }}"
    type: "{{ envsync_ssh_key_type }}"
    comment: "{{ envsync_user }}@{{ inventory_hostname }}"
    regenerate: full_idempotence
  become: true
  become_user: "{{ envsync_user }}"

- name: "Check if ssh public key for the {{ envsync_user }} user was added to the account management system."
  ansible.builtin.shell:
    cmd: |
         set -o pipefail
         "{{ get_public_keys_command }}" "{{ envsync_user }}" \
         | fgrep -f "{{ envsync_key_file_path }}.pub"
  register: envsync_user_authorized_public_keys
  changed_when: false
  failed_when: false
  when: use_ldap is true
  become: true
  become_user: "{{ envsync_user }}"

- name: "Fail when the ssh public key for the {{ envsync_user }} user is missing."
  ansible.builtin.debug:
    msg: |
         ***********************************************************************************************************
         IMPORTANT: Manual work!
         ***********************************************************************************************************
         Ansible created:
             {{ inventory_hostname }}:{{ envsync_key_file_path }}.pub
         But that public key is not yet available for the {{ envsync_user }} user
         in the output of the {{ get_public_keys_command }} command:
             stdout: {{ envsync_user_authorized_public_keys['stdout'] }}
             stderr: {{ envsync_user_authorized_public_keys['stderr'] }}
         Please check the account management system, add the public key for the user and re-run this role.
         ***********************************************************************************************************
  failed_when:
    - envsync_user_authorized_public_keys['rc'] >= 1
  when:
    - use_ldap | default(true) | bool
    - envsync_user_authorized_public_keys['rc'] >= 1

- name: "Assign ssh public key to ~/.ssh/authorized_keys for {{ envsync_user }}."
  ansible.posix.authorized_key:
    user: "{{ envsync_user }}"
    key: "file://{{ envsync_key_file_path }}.pub"
    state: present
    exclusive: true
  when:
    - not use_ldap | default(true) | bool
  become: true
  become_user: "{{ envsync_user }}"

- name: 'Deploy script to verify and if necessary fix permissions of the environment managed by the envsync account.'
  ansible.builtin.template:
    src: 'templates/hpc-environment-permissions.bash'
    dest: '/root/hpc-environment-permissions.bash'
    owner: 'root'
    group: 'root'
    mode: '0750'
  become: true

- name: 'Create cron job to execute script to verify and if necessary fix prmissions of the environment managed by the envsync account.'
  ansible.builtin.cron:
    name: Verify and fix permissions for HPC environment.
    weekday: '*'
    hour: '3'
    minute: '3'
    user: 'root'
    job: |
         /bin/bash -c '/root/hpc-environment-permissions.bash | /bin/logger'
    cron_file: 'hpc-environment-permissions'
  become: true

- name: 'Create cron job to synchronise the environment managed by the envsync account.'
  ansible.builtin.cron:
    name: Synchronise HPC environment.
    weekday: '*'
    hour: '4'
    minute: '4'
    user: "{{ envsync_user }}"
    job: |
         /usr/bin/sg '{{ envsync_group }}' -c '/bin/bash -c "export SOURCE_HPC_ENV="True"; . ~/.bashrc; hpc-environment-sync.bash -a | /bin/logger"'
    cron_file: 'hpc-environment-sync'
  become: true
...
