---
- name: "Create the repo folder structure for {{ this_distribution }}"
  ansible.builtin.file:
    path: "{{ main_repo_path }}/dnf/repos.d/{{ this_distribution }}"
    state: directory
    mode: '0750'
    owner: "{{ repo_user }}"
    group: "{{ repo_group }}"
  become: true

- name: "Configure main configurations for /{{ this_distribution }}"
  ansible.builtin.template:
    src: templates/dnf.conf.j2
    dest: "{{ main_repo_path }}/dnf/repos.d/{{ this_distribution }}.conf"
    owner: "{{ repo_user }}"
    group: "{{ repo_group }}"
    force: true
    mode: '0644'
  become: true

- name: "Create local_temp_repo_dir variable"
  ansible.builtin.set_fact:
    local_temp_repo_dir: "{{ playbook_dir }}/temp_repo_{{ this_distribution }}"

- name: "Remove local {{ local_temp_repo_dir }} directory if it exists"
  ansible.builtin.file:
    path: "{{ local_temp_repo_dir }}"
    state: absent
  changed_when: false # local files are only temporary, the actual change occurs in next task
  delegate_to: localhost
  connection: local

- name: "Create the {{ local_temp_repo_dir }} if missing"
  ansible.builtin.file:
    path: "{{ local_temp_repo_dir }}"
    state: directory
    mode: '0755'
  changed_when: false # local files are only temporary, the actual change occurs in following tasks
  delegate_to: localhost
  connection: local

- name: "Configure all options for all repos in {{ this_distribution }}"
  community.general.ini_file:
    path: "{{ local_temp_repo_dir }}/{{ item.0.file }}"
    section: "{{ item.0.id }}"
    no_extra_spaces: true
    create: true
    option: "{{ item.1 }}"
    value: "{{ item.0[item.1] }}"
    mode: '0644'
  loop: "{{ yum_repos[this_distribution]
          | product(options)
          | list }}"
  loop_control:
    label: "{{ item.0.file }} {{ item.1 }}"
  vars:
    options:
      - name
      - baseurl
      - mirrorlist
      - metalink
  when:
    - item.0.repo_server_download | bool | default(False)
    - item.0[item.1] is defined
  delegate_to: localhost
  connection: local
  changed_when: false # local files are only temporary, the actual change occurs in next task

- name: "Copy repo files to repo_servers"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ main_repo_path }}/dnf/repos.d/{{ this_distribution }}/"
    owner: "{{ repo_user }}"
    group: "{{ repo_group }}"
    mode: '0644'
  loop: "{{ lookup('fileglob', local_temp_repo_dir + '/*', wantlist=True) }}"
  become: true

- name: Get list of local files
  ansible.builtin.set_fact:
    local_files: "{{ lookup('fileglob', local_temp_repo_dir + '/*', wantlist=True) | map('basename') | list }}"
  delegate_to: localhost
  connection: local

- name: "Get list of remote repo files"
  ansible.builtin.find:
    paths: "{{ main_repo_path }}/dnf/repos.d/{{ this_distribution }}/"
    patterns: "*.repo"
  register: remote_repos
  become: true

- name: "Delete remote repo files not in local list"
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ remote_repos.files }}"
  when: item.path | basename not in local_files
  become: true
  loop_control:
    label: "{{ item.path }}"

- name: "Remove local {{ local_temp_repo_dir }} directory if it exists"
  ansible.builtin.file:
    path: "{{ local_temp_repo_dir }}"
    state: absent
  changed_when: false # local files are only temporary, the actual change occurs in next task
  delegate_to: localhost
  connection: local
...
