---
slurm_cluster_name: 'hyperchicken'
stack_domain: 'hpc.rug.nl'
stack_name: "{{ slurm_cluster_name }}_cluster"  # stack_name must match the name of the folder that contains this vars.yml file.
stack_prefix: 'hc'
stack_dtap_state: development
slurm_version: '24.11.7-1.el9.umcg'
slurm_partitions:
  - name: cpu_vm  # Must be in sync with group listed in Ansible inventory.
    default: yes
    nodes: "{{ stack_prefix }}-node-a01"  # Must be in sync with Ansible hostnames listed in inventory.
    extra_options: 'TRESBillingWeights="CPU=1.0,Mem=0.5G" DenyQos=ds-short,ds-medium,ds-long'
  - name: user_interface  # Must be in sync with group listed in Ansible inventory.
    default: no
    nodes: "{{ slurm_cluster_name }}"  # Must be in sync with Ansible hostnames listed in inventory.
    extra_options: 'TRESBillingWeights="CPU=1.0,Mem=1.0G" AllowQos=ds-short,ds-medium,ds-long'
repo_manager: 'pulp'
os_distribution: 'alma9'
os_minorversion: '.8'
figlet_font: 'lockergnome'
motd: "To solve or not to solve, that's the question."
#
# Cluster classification (used by `logs` and `login` roles)
#
cluster_class: 'development'

# Install auto-subgroup generate scripts
# depending on having `ladap` in `ldap_domains`
subgroup_directories_auto_is_enabled: true

#
# Ldap settings
#
use_ldap: true
use_sssd: true
ldap_domains:
#  stack:
#    uri: "ldaps://{{ stack_prefix }}-dai"
#    base: "dc={{ stack_name }},dc=local"
#    schema: rfc2307bis
#    min_id: 1000
#    max_id: 21999
#    user_object_class: posixAccount
#    user_name: uid
#    user_ssh_public_key: sshPublicKey
#    user_member_of: memberOf
#    group_member: member
#    create_ldap: true
  ladap:
    # must be FQDN or certificate authentication with LDAP server fails
    uri: ldaps://ladap.westeurope.cloudapp.azure.com
    base: dc=donbot_azure,dc=local
    # rfc2307bis for LADAP, because group members are stored in each group and
    # not in the user profile
    schema: rfc2307bis
    min_id: 37800000
    max_id: 37999999
    user_object_class: posixAccount
    user_name: mail
    user_ssh_public_key: sshPublicKey
    user_member_of: member
    group_object_class: groupofnames
    group_member: member
    # Path of the home directory should not be depending on the username (as it
    # can change). Instead we use %U to make it stable, unique (/home/[uid])
    # and persistent across systems
    override_homedir: '/home/%U'
  sram:
    uri: ldaps://sv-sram.id.rug.nl
    base: ou=sram-umcg,ou=users,o=id
    schema: rfc2307bis
    min_id: 70000000
    max_id: 72999999
    user_object_class: posixAccount
    user_name: uid
    user_ssh_public_key: sshPublicKey
    user_member_of: groupMembership
    group_member: member
  idvault:
    uri: ldaps://svrs.id.rug.nl
    base: ou=umcg,o=asds
    schema: rfc2307
    min_id: 50100000
    max_id: 55999999
    user_object_class: posixAccount
    user_name: uid
    user_ssh_public_key: sshPublicKey
    user_member_of: groupMembership
    user_expiration_date: loginExpirationTime
    group_member: memberUid
    group_object_class: groupofnames
cloud_image: AlmaLinux-9-GenericCloud-9.8-20260526
availability_zone: nova
enable_predictable_network_interface_names: true
stack_networks:
  - name: "{{ stack_prefix }}_internal_management"
    cidr: '10.10.1.0/24'
    router:
      next-hop-address: '10.10.1.1'
      external_network: external_unfiltered
    create: true
    mtu_size: '1450'
  - name: lustre  # DH5
    cidr: '172.23.12.0/22'
security_group_mods:
  - name: "{{ stack_prefix }}_storage"
    allow_ingress:
      - 172.23.15.186/32  # Lustre server
      - 172.23.15.187/32  # Lustre server
nameservers: [
  '8.8.4.4',  # Google DNS.
  '8.8.8.8',  # Google DNS.
]
local_admin_groups:
  - 'admin'
local_admin_users:
  - 'ger'
  - 'gerben'
  - 'henkjan'
  - 'kim'
  - 'marieke'
  - 'max'
  - 'morris'
  - 'pieter'
  - 'robin'
  - 'sandi'
  - 'steven'
  - 'wim'
  - 'wouter'
envsync_user: 'umcg-envsync'
envsync_group: 'umcg-depad'
functional_admin_group: 'umcg-funad'
hpc_env_prefix: '/apps'
sponsors:
  - name: umcg-research-it
    slurm_shares: 100
regular_groups:
  - name: "{{ envsync_group }}"
  - name: "{{ functional_admin_group }}"
  - name: 'umcg-atd'
    sponsor: umcg-research-it
  - name: 'umcg-gsad'
    sponsor: umcg-research-it
regular_users:
  - name: "{{ envsync_user }}"
    groups: ["{{ envsync_group }}"]
  - name: 'umcg-atd-dm'
    groups: ['umcg-atd']
  - name: 'umcg-gsad-dm'
    groups: ['umcg-gsad']
  - name: 'gvdvries'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd']
  - name: 'mbijlsma'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd']
  - name: 'mswertz'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd']
  - name: 'pneerincx'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd']
  - name: 'rkanninga'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd']
  - name: 'scimerman'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd']
  - name: 'umcg-molgenis'
    groups: ['users', 'umcg-atd', 'umcg-gsad']
sudoers:
  - who: ['%L-erdera']
    become: ['L-erdera-dm']
  - who: ['%L-gcc']
    become: ['L-gcc-dm']
  - who: ['%umcg-atd', '%umcg-gsad', '%umcg-gst']
    become: ['umcg-molgenis']
  - who: ['%umcg-atd']
    become: ['umcg-atd-dm']
  - who: ['%umcg-gsad']
    become: ['umcg-gsad-dm']
# Remote archive settings
remote_archive:
  - name: arc01
    local_top_level_mount: '/groups'
    groups:
      - 'umcg-atd'
    archive_user: 'umcg-atd-dm'
    archive_system: 'archive.surfsara.nl'
    archive_system_fingerprints:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBZilfH5KJk9dbYshGS9fnK+rkkIreVNEHqZatHjKGBm
      - ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBH+jkWREUSjl/NyAPcFBzLvJsDgN1ZupeCYvQ9LkoI1SZGVsIrH2W1eRhb8vMgn3noNfKclaXEiX4DR+lNBrLOA=
    archive_remote_top_dir: '/archive/umcg-atd-dm'
    recall_cron_script: 'cron_surf.sh.j2' # a cron script to trigger remote exectuion. Can be different for different types of remote archive.
#
# Shared storage related variables
#
pfs_mounts:
  - pfs: umcgst07
    source: '172.23.15.186@tcp15:172.23.15.187@tcp15:/umcgdh5'
    type: lustre
    rw_options: 'defaults,_netdev,flock'
    ro_options: 'defaults,_netdev,ro'
    machines: "{{ groups['sys_admin_interface'] }}"
    check_fs_free: '10%'
lfs_mounts:
  - lfs: home
    pfs: umcgst07
    rw_machines: "{{ groups['cluster'] }}"
  - lfs: tmp09
    pfs: umcgst07
    groups:
      - name: umcg-atd
      - name: umcg-gsad
      - name: L-erdera
      - name: L-gcc
    rw_machines: "{{ groups['user_interface'] + groups['deploy_admin_interface'] + groups['compute_node'] }}"
  - lfs: prm09
    pfs: umcgst07
    groups:
      - name: umcg-atd
      - name: umcg-gsad
      - name: L-erdera
      - name: L-gcc
    rw_machines: "{{ groups['user_interface'] }}"
  - lfs: env09
    pfs: umcgst07
    ro_machines: "{{ groups['compute_node'] + groups['user_interface'] }}"
    rw_machines: "{{ groups['deploy_admin_interface'] }}"
...
