---
slurm_cluster_name: 'fender'
slurm_cluster_domain: ''
stack_prefix: 'fd'
slurm_version: '17.11.9-2.umcg.el7'
mailhub: '192.168.0.5'
rewrite_domain: "{{ stack_prefix }}-sai{% if slurm_cluster_domain | length %}.{{ slurm_cluster_domain }}{% endif %}"
motd: "To solve or not to solve, that's the question."
vcompute_hostnames: "{{ stack_prefix }}-vcompute[01-12]"
vcompute_sockets: 16
vcompute_cores_per_socket: 1
vcompute_real_memory: 64264
vcompute_max_cpus_per_node: "{{ vcompute_sockets * vcompute_cores_per_socket - 2 }}"
vcompute_max_mem_per_node: "{{ vcompute_real_memory - vcompute_sockets * vcompute_cores_per_socket * 512 }}"
vcompute_local_disk: 0
vcompute_features: 'tmp10'
vcompute_ethernet_interfaces:
  - 'eth0'
  - 'eth1'
ui_hostnames: "{{ slurm_cluster_name }}"
ui_sockets: 4
ui_cores_per_socket: 1
ui_real_memory: 7821
ui_local_disk: 0
ui_features: 'prm10,tmp10'
ui_ethernet_interfaces:
  - 'eth0'
  - 'eth1'
ssh_host_signer_ca_private_key: "{{ ssh_host_signer_ca_keypair_dir }}/ca-key-production-ebi"
use_ldap: yes
create_ldap: yes
uri_ldap: fd-dai
uri_ldaps: fd-dai
ldap_port: 389
ldaps_port: 636
ldap_base: dc=hpc,dc=rug,dc=nl
ldap_binddn: cn=admin,dc=hpc,dc=rug,dc=nl
ldap_domain: hpc.rug.nl
key_name: Gerben
image_cirros: cirros-0.3.4-x86_64-disk.img
image_centos7: centos7
cloud_user: centos
flavor_nano: s1.nano
flavor_tiny: s1.tiny
flavor_ui: s1.large
flavor_vcompute: s1.gargantuan
public_net_id: ext-net-37
public_ip_addresses:
  corridor: '193.62.55.161'
private_net_id: Solve-RD_private
private_subnet_id: Solve-RD_subnet
private_storage_net_id: net_provider_vlan3126
private_storage_subnet_id: subnet3126
security_group_id: SSH-and-ping-2
slurm_ldap: true
fuse_mountpoint: /groups/solve-rd/prm10/EGAD00001005352/
availability_zone: AZ_1
storage_availability_zone: nova
local_volume_size: 1
nameservers: [
  '/em-isi-3126.ebi.ac.uk/10.35.126.201',  # Local DNS lookups for shared storage.
  '8.8.4.4',  # Google DNS.
  '8.8.8.8',  # Google DNS.
]
local_admin_groups:
  - 'admin'
  - 'docker'
local_admin_users:
  - 'egon'
  - 'centos'
  - 'henkjan'
  - 'marieke'
  - 'morris'
  - 'pieter'
  - 'wim'
  - 'gerben'
envsync_user: 'envsync'
envsync_group: 'depad'
hpc_env_prefix: '/apps'
regular_groups:
  - 'users'
  - 'depad'
  - 'solve-rd'
  - 'umcg-atd'
regular_users:
  - user: 'envsync'
    groups: ['depad']
  - user: 'solve-rd-dm'
    groups: ['solve-rd']
    sudoers: '%solve-rd'
  - user: 'umcg-atd-dm'
    groups: ['umcg-atd']
    sudoers: '%umcg-atd'
  - user: 'solve-rd-ateambot'
    groups: ['solve-rd']
    sudoers: '%solve-rd'
  - user: 'gvdvries'
    groups: ['users', 'depad','umcg-atd', 'solve-rd']
  - user: 'mbijlsma'
    groups: ['users', 'depad','umcg-atd', 'solve-rd']
  - user: 'mswertz'
    groups: ['users', 'depad','umcg-atd', 'solve-rd']
  - user: 'pneerincx'
    groups: ['users', 'depad','umcg-atd', 'solve-rd']
  - user: 'rkanninga'
    groups: ['users', 'depad','umcg-atd', 'solve-rd']
  - user: 'ljohansson'
    groups: ['users', 'depad','umcg-atd', 'solve-rd']
  - user: 'ddanis'
    groups: ['users', 'solve-rd']
  - user: 'ksablauskas'
    groups: ['users', 'solve-rd']
  - user: 'wsteyaert'
    groups: ['users', 'solve-rd']
  - user: 'slaurie'
    groups: ['users', 'solve-rd']
  - user: 'mpauper'
    groups: ['users', 'solve-rd']
  - user: 'jvdvelde'
    groups: ['users', 'solve-rd']
  - user: 'fmusacchia'
    groups: ['users', 'solve-rd']
  - user: 'dspalding'
    groups: ['users', 'solve-rd']
  - user: 'psivakumar'
    groups: ['users', 'solve-rd']
  - user: 'fandrade'
    groups: ['users', 'solve-rd']
  - user: 'gdemidov'
    groups: ['users', 'solve-rd']
  - user: 'amohan'
    groups: ['users', 'solve-rd']
  - user: 'cthomas'
    groups: ['users', 'solve-rd']
  - user: 'mbenjamins'
    groups: ['users','depad', 'umcg-atd', 'solve-rd']
  - user: 'lmatalonga'
    groups: ['users', 'solve-rd']
  - user: 'gbullich'
    groups: ['users', 'solve-rd']
  - user: 'ebenetti'
    groups: ['users', 'solve-rd']
  - user: 'kdelange'
    groups: ['users', 'depad', 'umcg-atd', 'solve-rd']
  - user: 'sli'
    groups: ['users', 'solve-rd']
  - user: 'rschuele'
    groups: ['users', 'solve-rd']
  - user: 'jvandrovcova'
    groups: ['users', 'solve-rd']
pfs_mounts: [
  { pfs: 'ecst02',
    source: 'em-isi-3126.ebi.ac.uk:/ifs/Solve-RD',
    type: 'nfs',
    rw_options: 'defaults,_netdev,noatime,nodiratime',
    ro_options: 'defaults,_netdev,noatime,nodiratime,ro' },
]
lfs_mounts: [
  { lfs: 'home',
    pfs: 'ecst02',
    machines: "{{ groups['cluster'] }}" },
  { lfs: 'tmp10',
    pfs: 'ecst02',
    groups: ['umcg-atd', 'solve-rd'] },
  { lfs: 'prm10',
    pfs: 'ecst02',
    groups: ['umcg-atd', 'solve-rd'] },
  { lfs: 'env10',
    pfs: 'ecst02',
    machines: "{{ groups['compute-vm'] + groups['user-interface'] }}" },
]
...
