---
# gpu_driver_version has no defaults: must be specified for specific machines in static_inventory/{{ stackname }}.yml
gpu_url_dir: 'https://download.nvidia.com/XFree86/Linux-x86_64/{{ gpu_driver_version }}/'
gpu_runfile: 'NVIDIA-Linux-x86_64-{{ gpu_driver_version }}.run'
nvidia_user: nvidia
nvidia_uid: 601       # a regular user with UID >500 and <1000, but no login
nvidia_group: nvidia
nvidia_gid: 601
...
