---
- name: 'Install figlet.'
  ansible.builtin.package:
    state: latest
    update_cache: true
    name: figlet
  become: true

- name: 'Install custom figlet fonts.'
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/usr/share/figlet/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - 'cyberlarge.flf'
    - 'doh.flf'
    - 'lockergnome.flf'
    - 'ogre.flf'
    - 'slant.flf'
    - 'speed.flf'
  become: true

- name: 'Create MOTD.'
  ansible.builtin.include_tasks:
    file: 'create_motd.yml'
  vars:
    figlet_cmd: 'figlet -w 120 -f "{{ figlet_font }}" "{{ ansible_hostname }}"'
...
