---
- name: Deploy backup script
  ansible.builtin.template:
    src: "templates/ogm_cron_make_backup.sh.j2"
    dest: "~umcg-ogm-dm/make_backup-{{ srvid }}.sh"
    owner: umcg-ogm-dm
    group: umcg-ogm-dm
    mode: '0750'
  with_items: "{{ ogm_servers | default([]) }}"
  vars:
    srvid: "{{ item.server.split('.')[0] }}"
  when:
    - item.prm_location is defined
    - item.server is defined
    - item.user is defined
  become: true

- name: Deploy backup cleanup script
  ansible.builtin.template:
    src: "templates/ogm_cron_clean_psql_backups.sh.j2"
    dest: "~umcg-ogm-dm/manage_psql_backups-{{ srvid }}.sh"
    owner: umcg-ogm-dm
    group: umcg-ogm-dm
    mode: '0750'
  with_items: "{{ ogm_servers | default([]) }}"
  vars:
    srvid: "{{ item.server.split('.')[0] }}"
  when:
    - item.prm_location is defined
    - item.server is defined
    - item.user is defined
    - item.psql_dump_location is defined
  become: true

- name: 'Create cron job to make daily backup with the script'
  ansible.builtin.cron:
    name: "Backup_OGM_data-{{ srvid }}  # Unique ID required to update existing cronjob: do not modify."
    weekday: '*'
    hour: "03" # we fix hour for different tasks
    minute: "{{ 59 | random(seed=inventory_hostname) }}" # but change minutes to random value per hostname
    user: "umcg-ogm-dm"
    job: >
         /bin/bash -c 'parallax.sh --command="~/make_backup-{{ srvid }}.sh >> ~/make_backup-{{ srvid }}.sh.log"
                                   --lock-dir="{{ item.prm_location }}/lock_dirs/make_backup-{{ srvid }}/"
                                   --logger-tag=ogm'
    cron_file: "ogm"
  with_items: "{{ ogm_servers | default([]) }}"
  when:
    - item.prm_location is defined
    - item.server is defined
    - item.user is defined
  vars:
    srvid: "{{ item.server.split('.')[0] }}"
  become: true

- name: 'Create cron job to make daily clean psql backups with the script'
  ansible.builtin.cron:
    name: "Clean_OGM_data-{{ srvid }}  # Unique ID required to update existing cronjob: do not modify."
    weekday: '*'
    hour: "06" # we fix hour for different tasks
    minute: "{{ 59 | random(seed=inventory_hostname) }}" # but change minutes to random value per hostname
    user: "umcg-ogm-dm"
    job: >
         /bin/bash -c 'parallax.sh --command="~/manage_psql_backups-{{ srvid }}.sh >> ~/manage_psql_backups-{{ srvid }}.sh.log"
                                   --lock-dir="{{ item.prm_location }}/lock_dirs/manage_psql-{{ srvid }}/"
                                   --logger-tag=ogm'
    cron_file: 'ogm'
  with_items: "{{ ogm_servers | default([]) }}"
  vars:
    srvid: "{{ item.server.split('.')[0] }}"
  when:
    - item.prm_location is defined
    - item.server is defined
    - item.user is defined
    - item.psql_dump_location is defined
  become: true

- name: 'Make sure that cron has right environment variables'
  ansible.builtin.cron:
    name: PATH
    env: true
    user: "umcg-ogm-dm"
    job: "/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin"
    cron_file: "ogm"
  when: ogm_servers is defined
  become: true
...
