---
- name: Check the file system type of the device.
  ansible.builtin.command: "lsblk -n -o FSTYPE {{ volume['device'] }}"
  register: device_status
  changed_when: false

- name: Check the file system label of the device.
  ansible.builtin.command: "lsblk -n -o LABEL {{ volume['device'] }}"
  register: device_label
  changed_when: false
  when:
    - volume['label'] is defined

- name: Check the mount point.
  ansible.builtin.command: "mountpoint {{ volume['mount_point'] }}"
  register: mount_point_status
  failed_when: mount_point_status.rc not in [0, 1, 32]
  changed_when: false

- name: Create a filesystem on the device.
  community.general.filesystem:
    fstype: "{{ volume['type'] }}"
    dev: "{{ volume['device'] }}"
    opts: "{% if volume['label'] is defined %}-L {{ volume['label'] }}{% endif %}"
    force: false
    resizefs: true
  when:
    #
    # Nothing is mounted at the mount point
    # and when the device is unformatted.
    #
    - mount_point_status['rc'] != 0
    - device_status['stdout'] != volume['type']
  become: true

- name: Fail when volume label is too long.
  ansible.builtin.debug:
    msg: |
         FATAL: Volume label '{{ volume['label'] }}' is too long;
                {{ volume['label'] | length }} exceeds max length of {{ max_label_length }} characters.
  vars:
    max_label_length: >-  # noqa jinja[spacing]
      {%- if volume['type'] | ansible.builtin.regex_search('^ext[0-9]+') -%}
      16
      {%- elif volume['type'] == 'xfs' -%}
      12
      {%- endif -%}
  when:
    - mount_point_status['rc'] != 0
    - volume['label'] is defined
    - device_label['stdout'] != volume['label']
    - volume['label'] | length > max_label_length | int
  failed_when:
    - volume['label'] | length > max_label_length | int

- name: Label existing, unmounted ext file system.
  ansible.builtin.shell:
    cmd: |
         e2label {{ volume['device'] }} {{ volume['label'] }} && e2label {{ volume['device'] }}
  register: e2label_result
  changed_when: e2label_result['stdout'] != device_label['stdout']
  when:
    - mount_point_status['rc'] != 0
    - volume['label'] is defined
    - device_label['stdout'] != volume['label']
    - volume['type'] is ansible.builtin.search('^ext[0-9]+')
  become: true

- name: Label existing, unmounted xfs file system.
  ansible.builtin.shell:
    cmd: |
         xfs_admin -L '{{ volume['label'] }}' '{{ volume['device'] }}' && udevadm trigger && lsblk -n -o LABEL '{{ volume['device'] }}'
  register: xfs_admin_result
  changed_when: xfs_admin_result['stdout_lines'][-1] != device_label['stdout']  # -1 refers to the last line.
  when:
    - mount_point_status['rc'] != 0
    - volume['label'] is defined
    - device_label['stdout'] != volume['label']
    - volume['type'] == 'xfs'
  become: true
...
