---
- name: Install tools to work with block devices and mount points.
  ansible.builtin.package:
    state: 'latest'
    update_cache: true
    name:
      - util-linux  # Will also install util-linux-core
  when: local_mounts | default([]) | length > 0
  become: true

- name: Install tools to work with Multiple Devices a.k.a. software RAIDs.
  ansible.builtin.package:
    state: 'latest'
    update_cache: true
    name:
      - mdadm
  when: local_mounts | default([]) | selectattr('md', 'defined') | length > 0
  become: true

- name: Create Multiple Devices a.k.a. software RAIDs.
  ansible.builtin.include_tasks:
    file: md.yml
  loop: "{{ local_mounts | default([]) }}"
  loop_control:
    loop_var: volume
    index_var: idx
  when: volume['md'] is defined

- name: Get unstable device name from perc cli utility and update facts.
  ansible.builtin.include_tasks:
    file: perc.yml
  loop: "{{ local_mounts | default([]) }}"
  loop_control:
    loop_var: volume
    index_var: idx
  when: volume['perc_controller'] is defined

- name: Check if file system source is a device.
  ansible.builtin.stat:
    path: "{{ item.device }}"
    follow: true
  register: local_storage_device_stat
  loop: "{{ local_mounts | default([]) }}"
  become: true

- name: Create a file system on unformatted device.
  ansible.builtin.include_tasks:
    file: create_filesystem_on_device.yml
  when:
    - local_storage_device_stat['results']
        | selectattr('item', 'equalto', volume)
        | map(attribute='stat')
        | map(attribute='isblk')
        | first is true
  loop: "{{ local_mounts | default([]) }}"
  loop_control:
    loop_var: volume

- name: Mount the local file system.
  ansible.builtin.include_tasks:
    file: mount_filesystem.yml
  vars:
    volume_src: "{% if volume['label'] is defined %}LABEL={{ volume['label'] }}{% else %}{{ volume['device'] }}{% endif %}"
  loop: "{{ local_mounts | default([]) }}"
  loop_control:
    loop_var: volume
    label: "Mounting {{ volume['type'] }} file system from {{ volume_src }} on {{ volume['mount_point'] }} with opts: {{ volume['mount_options'] }}}"

- name: Create sub folders on local file systems.
  ansible.builtin.include_tasks:
    file: create_sub_folders.yml
  vars:
    mount_point: "{{ item.1.mount_point }}"
    folders: "{{ item.1.folders | list }}"
  when:
    - local_mounts is defined
    - local_mount_subfolders is defined
    - item.0.mount_point == item.1.mount_point
    - inventory_hostname in item.1.machines
  loop: "{{ local_mounts | product(local_mount_subfolders) | list }}"
...
