#
# This pulp_server role depends on
#     pulp.pulp_installer.pulp_all_services
# which installs pulp itself.
#
# In this role we
#  * Create a {{ repo_management_user }} user.
#  * Install/check additional tooling like:
#      * pulp-cli, which is the commandline interface to interact with a Pulp instance.
#      * httpie, a commandline interface to interface with the Pulp API using GET/POST/PUT HTTP calls.
#  * Configure some repositories and their remotes.
#  * Sync repositories for the first time to create an initial repository version,
#    create a publications for the initial repository version and distribute that publication.
# Creating additional repository version, new publications and updating distribution is manual work for
# the {{ repo_management_user }} and outside the scope for this pulp_server role.
---
- name: Get checksum of Pulp root certificate on repo server.
  ansible.builtin.stat:
    path: "{{ pulp_root_cert_path_on_repo_server }}"
    checksum_algorithm: sha1
  register: repo_server_pulp_root_certificate
  become: true

- name: Check the Pulp root certificate on local machine
  ansible.builtin.stat:
    path: "{{ pulp_root_cert_path_on_control_host }}"
  register: file_details
  delegate_to: localhost
  connection: local

- name: Exit with warning if Pulp root certificate is missing on local machine.
  ansible.builtin.debug:
    msg: |
         ***********************************************************************************************************
         IMPORTANT: Manual work!
         ***********************************************************************************************************
                    The Pulp root certificate file is missing in:
                        {{ pulp_root_cert_path_on_control_host }}
                    Create the folder for the Pulp root certificate if it does not exist yet.
                    This role will have created a new Pulp root certificate on the repo server automatically.
                    Now, copy the certificate from the pulp server location:
                        {{ pulp_root_cert_path_on_repo_server }}
                    to:
                        {{ pulp_root_cert_path_on_control_host }}
                    on the control host where this role was executed and re-run this role.
         ***********************************************************************************************************
  when: not file_details.stat.exists
  failed_when: not file_details.stat.exists

- name: Checking if Pulp root certificate must be updated.
  ansible.builtin.debug:
    msg: |
         ***********************************************************************************************************
         IMPORTANT: Manual work!
         ***********************************************************************************************************
                    The Pulp root certificate on the Pulp repo server in:
                        {{ pulp_root_cert_path_on_repo_server }}
                    Differs from the Pulp root certificate on the Ansible control host in:
                        {{ pulp_root_cert_path_on_control_host }}
                    Check which one is correct and update the other one.
         ***********************************************************************************************************
  when: repo_server_pulp_root_certificate.stat.checksum | default('Missing Pulp root certificate checksum on repo server', true)
        != lookup('unvault', pulp_root_cert_path_on_control_host) | hash('sha1')
  failed_when: repo_server_pulp_root_certificate.stat.checksum | default('Missing Pulp root certificate checksum on repo server', true)
               != lookup('unvault', pulp_root_cert_path_on_control_host) | hash('sha1')

- name: Add pulp web server root certificate to list of trusted root certificates.
  ansible.builtin.copy:
    src: "{{ stack_name }}/{{ item }}_pulp_root.crt"
    dest: /etc/pki/ca-trust/source/anchors/
    owner: root
    group: root
    mode: '0600'
  with_items: "{{ groups['repo'] }}"
  become: true
  notify: update-ca-trust

- name: Flush handlers.
  ansible.builtin.meta: flush_handlers

#
## IMPORTANT:
## The (root) certificates above are used by the nginx web server serving content to Pulp clients,
## which use an encrypted connection over HTTPS to access content.
##
## Below this comment we use HTTP on localhost and disable any SSL certificate validation for the Pulp API,
## because the Pulp API server as well as the client components to interact with the API are all written in Python
## and adding a CA root certificate to these various Python components is a big inconsistent mess.
##  * Pulp API is served by a gunicorn web server written in Python.
##  * pulp-cli installed on the repo server is written in Python.
##  * The calls in the tasks below use the pulp.sequeezer Ansible collection, which is also written Python.
##
#

- name: Install packages.
  ansible.builtin.package:
    state: 'latest'
    update_cache: true
    name:
      - nano
      - httpie
      - jq
      - curl
  become: true

- name: "Create local private group for {{ repo_management_user }} user's home dir."
  ansible.builtin.group:
    name: "{{ repo_management_user }}"                 # Use same name as user's account name for user's private group.
    gid: "{{ auth_users[repo_management_user].uid }}"  # Use same GID as user's UID for user's private group.
    state: present
  become: true

- name: Create /admin root dir for the home dirs of local admin users.
  ansible.builtin.file:
    path: '/admin'
    owner: root
    group: root
    mode: '0755'
    state: directory
  become: true

- name: "Create local {{ repo_management_user }} user."
  ansible.builtin.user:
    name: "{{ repo_management_user }}"
    uid: "{{ auth_users[repo_management_user].uid }}"
    comment: "{{ auth_users[repo_management_user].comment }}"
    group: "{{ repo_management_user }}"
    groups:
      # repo_management_user must be a member to prevent a permission denied error on '/etc/pulp/cli.toml'
      - "{{ pulp_group }}"  # Default from pulp.pulp_installer role.
    home: "/admin/{{ repo_management_user }}"
    append: false
  become: true

- name: "Initialize {{ repo_management_user }} account creating home dir if it did not exist yet."
  ansible.builtin.command:
    cmd: "mkhomedir_helper {{ repo_management_user }} 0077"
    creates: "/admin/{{ repo_management_user }}"
  become: true

- name: "Allow passwordless sudo to the {{ repo_management_user }} account for Pulp admin users."
  ansible.builtin.lineinfile:
    dest: '/etc/sudoers'
    line: "%admin    ALL=({{ repo_management_user }})    NOPASSWD:ALL"
    owner: root
    group: root
    mode: '0440'
  become: true

- name: "Copy pulp-cli-requirements.txt to {{ repo_management_user }} user's home dir."
  ansible.builtin.copy:
    #
    # Update can be created using the following commands as repo_management_user on the repo server:
    #   repo_management_user@repo> source /admin/repo_management_user/pulp-cli.venv/bin/activate
    #   repo_management_user@repo> pip install --upgrade pulp-cli
    #   repo_management_user@repo> pip freeze > pulp-cli-requirements.txt
    #
    src: "files/pulp-cli-requirements-{{ os_distribution }}.txt"
    dest: "/admin/{{ repo_management_user }}/pulp-cli-requirements.txt"
    owner: "{{ repo_management_user }}"
    group: "{{ repo_management_user }}"
    mode: '0644'
  become: true
  become_user: "{{ repo_management_user }}"

- name: "Install pulp-cli from PyPi using pip and into a dedicated virtualenv in the {{ repo_management_user }} user's home."
  ansible.builtin.pip:
    requirements: "/admin/{{ repo_management_user }}/pulp-cli-requirements.txt"
    virtualenv_command: 'python3 -m venv'
    virtualenv: "/admin/{{ repo_management_user }}/pulp-cli.venv"
  become: true
  become_user: "{{ repo_management_user }}"

- name: Create folders for config files.
  ansible.builtin.file:
    name: "{{ item }}"
    owner: "{{ repo_management_user }}"
    group: "{{ repo_management_user }}"
    mode: '0750'
    state: 'directory'
  with_items:
    - "/admin/{{ repo_management_user }}/.config/"
    - "/admin/{{ repo_management_user }}/.config/pulp/"
  become: true
  become_user: "{{ repo_management_user }}"

- name: "Deploy ~.netrc file for {{ repo_management_user }} user."
  ansible.builtin.template:
    src: templates/repo_management_user.netrc.j2
    dest: "/admin/{{ repo_management_user }}/.netrc"
    mode: '0600'
    owner: "{{ repo_management_user }}"
    group: "{{ repo_management_user }}"
  become: true
  become_user: "{{ repo_management_user }}"

- name: "Deploy ~.config/pulp/cli.toml file for {{ repo_management_user }} user."
  ansible.builtin.template:
    src: templates/repo_management_user.cli.toml.j2
    dest: "/admin/{{ repo_management_user }}/.config/pulp/cli.toml"
    mode: '0600'
    owner: "{{ repo_management_user }}"
    group: "{{ repo_management_user }}"
  become: true
  become_user: "{{ repo_management_user }}"

- name: "Delete deprecated ~.config/pulp/settings.toml."
  ansible.builtin.file:
    path: "/admin/{{ repo_management_user }}/.config/pulp/settings.toml"
    state: absent
  become: true
  become_user: "{{ repo_management_user }}"
  when: os_distribution == 'rocky9'

- name: Read status from pulp API server and refresh API cache.
  pulp.squeezer.status:
    pulp_url: "{{ pulp_api_baseurl }}"
    username: "{{ pulp_api_user }}"
    password: "{{ pulp_api_password }}"
    validate_certs: false
    refresh_api_cache: true
  register: pulp_status
  vars:
    ansible_python_interpreter: "/admin/{{ repo_management_user }}/pulp-cli.venv/bin/python3"
  become: true
  become_user: "{{ repo_management_user }}"
  no_log: true

- name: Report pulp status.
  ansible.builtin.debug:
    var: pulp_status

- name: Manage repos.
  ansible.builtin.include_tasks: manage_repo.yml
  loop_control:
    label: "{{ pulp_repo.name }}"
    loop_var: pulp_repo
  loop: "{{ pulp_repos[os_distribution] | flatten(levels=1) }}"

- name: Deploy pulp-init.bash with code to manage Pulp repos.
  ansible.builtin.template:
    src: pulp-init.bash.j2
    dest: "/admin/{{ repo_management_user }}/pulp-init.bash"
    owner: "{{ repo_management_user }}"
    group: "{{ repo_management_user }}"
    mode: '0640'
  become: true
  become_user: "{{ repo_management_user }}"

- name: Incomplete pulp squeezer support notification.
  ansible.builtin.debug:
    msg: |
         ***********************************************************************************************************
         IMPORTANT: Manual work!
         ***********************************************************************************************************
         This is as far as we can get with the current limited support for RPM repositories in pulp-sequeezer.
         You will need to login to {{ inventory_hostname }} and use the pulp-cli as user {{ repo_management_user }}
         and
          * For repos that without upstream remote: upload RPM files to Pulp creating artifacts,
                                                    create RPMs in Pulp from the artifacts
                                                    and finally add the Pulp RPMs to the the Pulp RPM repository.
            (Syncing with remotes or adding RPMs automatically creates new repository versions.)
          * Create a new publication from the last repository version.
          * Create a distribution based on the new publication if it did not exist yet
            or update the existing distribution to serve the new publication.
         For instructions and examples see:
            .../league-of-robots/documentation/Configuring_Pulp.md
         ***********************************************************************************************************
  failed_when: true  # Always fail to get attention and inform user the work is not complete/done.
...
