---
- name: Print help options
  ansible.builtin.debug:
    msg: >
      this role supports following tags:
       - test    # for testing / validating that the connection with remote log
                 # server is working and that logs get correctly transferred
       - always
  run_once: true  # noqa run-once
  delegate_to: localhost
  connection: local
  tags:
    - help
    - never

- name: Stop the playbook
  ansible.builtin.meta: end_play
  tags:
    - help
    - never

- name: Compile the list of logs server names
  ansible.builtin.set_fact:
    cluster_class_servers: "{{ cluster_class_servers | default([]) + [item.name] }}"
  loop: "{{ logs_server_public_networks[cluster_class] }}"
  when: cluster_class is defined and cluster_class|length>0
  register: rsys_ext_ips
  delegate_to: localhost
  connection: local
  run_once: true
  tags:
    - always
    - test

- name: "Set proxy host (jumphost or AI_PROXY)"
  ansible.builtin.set_fact:
    proxy_host: >-
      {{
        (groups.jumphost | default([]) | first)
        | default(lookup('env', 'AI_PROXY'))
      }}

- name: Open logs server firewall for each client
  ansible.builtin.include_tasks:
    file: firewall.yml
  when: ( cluster_class is defined and ( cluster_class|length>0 ) ) or
        ( rsyslog_external_servers is defined and ( rsyslog_external_servers|length>0 ))

- name: Deploy rsyslog client
  ansible.builtin.include_tasks:
    file: deploy.yml
  when: ( cluster_class is defined and ( cluster_class|length>0 ) ) or
        ( rsyslog_external_servers is defined and ( rsyslog_external_servers|length>0 ))

- name: Test rsyslog client
  ansible.builtin.include_tasks:
    file: test.yml
  when: ( cluster_class is defined and ( cluster_class|length>0 ) ) or
        ( rsyslog_external_servers is defined and ( rsyslog_external_servers|length>0 ))
  tags:
    - always
    - test
...
