---
- name: Running update-ca-trust when certificates have changed.
  ansible.builtin.command:
    cmd: update-ca-trust extract
  changed_when: true
  become: true
  listen: pulp_client_update-ca-trust
...
