---
stack_prefix: 'jenkins'
stack_name: "{{ stack_prefix }}_server"  # stack_name must match the name of the folder that contains this vars.yml file.
cloud_image: AlmaLinux-9-GenericCloud-9.8-20260526
availability_zone: nova
os_distribution: 'alma9'
repo_manager: 'none'
stack_networks:
  - name: "{{ stack_prefix }}_internal_management"
    cidr: '10.10.1.0/24'
    router:
      next-hop-address: '10.10.1.1'
      external_network: external
    create: true
    mtu_size: '1450'
nameservers: [
  '8.8.4.4',  # Google DNS.
  '8.8.8.8',  # Google DNS.
]
local_admin_groups:
  - 'admin'
local_admin_users:
  - 'gerben'
  - 'henkjan'
  - 'marieke'
  - 'morris'
  - 'pieter'
  - 'sandi'
  - 'wim'
use_ldap: false
create_ldap: false
use_sssd: false
#
# Jumphosts from other stack-name infra groups.
# We will restrict SSH login on port 22 to these jumphosts using OpenStack security rules.
#
external_jumphosts:
  - group: vaxtron_cluster
    hosts:
    - hostname: foyer
      network: external
  - group: talos_cluster
    hosts:
      - hostname: reception
        network: vlan16
  - group: hyperchicken_cluster
    hosts:
      - hostname: portal
        network:  external_unfiltered
  - group: nibbler_cluster
    hosts:
      - hostname: tunnel
        network: vlan16
  - group: wingedhelix_cluster
    hosts:
      - hostname: wh-porch
        network: vlan16
  - group: betabarrel_cluster
    hosts:
      - hostname: bb-porch
        network: vlan16
  - group: copperfist_cluster
    hosts:
      - hostname: cf-porch
        network: external
jenkins_plugins:
  - warnings-ng
  - name: git
    version: 5.10.1
  - name: branch-api
    version: 2.1280.v0d4e5b_b_460ef
  - name: cloudbees-folder
    version: 6.1100.ve9eed61d16c4
  - name: github-branch-source
    version: 1967.1970.vd86979736546
  - name: analysis-model-api
    version: 14.14.0-1004.vf53c9efb_f455
  - name: github-api
    version: 1.330-492.v3941a_032db_2a_
  - name: git-client
    version: 6.6.1
  - name: github
    version: 1.47.0
  - name: matrix-auth
    version: 3.3
  - name: workflow-api
    version: 1413.v2ff1a_5e720fa_
  - name: workflow-job
    version: 1590.v49101d088542
  - name: workflow-multibranch
    version: 821.vc3b_4ea_780798
  - name: workflow-basic-steps
    version: 1098.v808b_fd7f8cf4
  - name: workflow-durable-task-step
    version: 1479.v56e587f413a_7
  - name: workflow-scm-step
    version: 466.va_d69e602552b_
  - name: pipeline-stage-step
    version: 345.va_96187909426
jenkins_plugins_install_dependencies: true
jenkins_prefer_lts: true
jenkins_shellcheck_version: 0.8.0
jenkins_url: 'http://localhost:8080/'
jenkins_cli_dest: '/opt/jenkins-cli.jar'
jenkins_xml_dest: '/var/lib/jenkins/xml_files/'
jenkins_projects: 
  - 'NGS_RNA'
  - 'ConcordanceCheck'
...
