---
- name: Set selinux in permissive mode
  ansible.posix.selinux:
    policy: targeted
    state: permissive
  become: true

- name: Install some standard software
  ansible.builtin.package:
    state: latest
    update_cache: true
    name: "{{ cluster_common_packages[distro] }}"
  vars:
    distro: "{{ ansible_facts['os_family'] + ansible_facts['distribution_major_version'] }}"
  tags:
    - software
  become: true

- name: Create sub dirs in /etc/skel/.
  ansible.builtin.file:
    path: "/etc/skel/{{ item['path'] }}"
    owner: root
    group: root
    mode: "{{ item['mode'] }}"
    state: directory
  loop:
    - path: .ssh
      mode: '0700'
    - path: .ssh/tmp
      mode: '0700'
  become: true

- name: Add custom config files to /etc/skel/.
  ansible.builtin.copy:
    src: "skel/{{ item['path'] }}"
    dest: "/etc/skel/{{ item['path'] }}"
    owner: root
    group: root
    mode: "{{ item['mode'] }}"
  loop:
    - path: .bashrc
      mode: '0644'
    - path: .screenrc
      mode: '0644'
    - path: .ssh/config
      mode: '0600'
    - path: .ssh/tmp/README
      mode: '0600'
  become: true
...
