---
ip_addresses:
  nb-dai:
    vlan1068:
      address: 172.23.60.31
      netmask: /32
    vlan1073:
      address: 172.23.14.112
      netmask: /32
    vlan1338:
      address: 172.23.69.157
      netmask: /32
    vlan985:
      address: 172.23.59.250
      netmask: /32
  nb-node-a01:
    vlan1068:
      address: 172.23.60.6
      netmask: /32
    vlan1338:
      address: 172.23.69.21
      netmask: /32
    vlan985:
      address: 172.23.59.95
      netmask: /32
  nb-node-a02:
    vlan1068:
      address: 172.23.60.29
      netmask: /32
    vlan1338:
      address: 172.23.69.80
      netmask: /32
    vlan985:
      address: 172.23.59.90
      netmask: /32
  nb-node-a03:
    vlan1068:
      address: 172.23.60.15
      netmask: /32
    vlan1338:
      address: 172.23.69.76
      netmask: /32
    vlan985:
      address: 172.23.59.213
      netmask: /32
  nb-node-a04:
    vlan1068:
      address: 172.23.60.16
      netmask: /32
    vlan1338:
      address: 172.23.69.48
      netmask: /32
    vlan985:
      address: 172.23.59.225
      netmask: /32
  nb-node-b01:
    vlan1068:
      address: 172.23.60.22
      netmask: /32
    vlan1338:
      address: 172.23.69.79
      netmask: /32
    vlan985:
      address: 172.23.59.247
      netmask: /32
  nb-node-c01:
    vlan1068:
      address: 172.23.60.26
      netmask: /32
    vlan1338:
      address: 172.23.69.138
      netmask: /32
  nb-node-c02:
    vlan1068:
      address: 172.23.60.13
      netmask: /32
    vlan1338:
      address: 172.23.69.51
      netmask: /32
  nb-node-c03:
    vlan1068:
      address: 172.23.60.25
      netmask: /32
    vlan1338:
      address: 172.23.69.54
      netmask: /32
  nb-node-c04:
    vlan1068:
      address: 172.23.60.18
      netmask: /32
    vlan1338:
      address: 172.23.69.185
      netmask: /32
  nb-node-c05:
    vlan1068:
      address: 172.23.60.12
      netmask: /32
    vlan1338:
      address: 172.23.69.24
      netmask: /32
  nb-node-c06:
    vlan1068:
      address: 172.23.60.20
      netmask: /32
    vlan1338:
      address: 172.23.69.193
      netmask: /32
  nb-node-c07:
    vlan1068:
      address: 172.23.60.10
      netmask: /32
    vlan1338:
      address: 172.23.69.62
      netmask: /32
  nb-node-c08:
    vlan1068:
      address: 172.23.60.5
      netmask: /32
    vlan1338:
      address: 172.23.69.200
      netmask: /32
  nb-node-c09:
    vlan1068:
      address: 172.23.60.17
      netmask: /32
    vlan1338:
      address: 172.23.69.130
      netmask: /32
  nb-node-c10:
    vlan1068:
      address: 172.23.60.3
      netmask: /32
    vlan1338:
      address: 172.23.69.248
      netmask: /32
  nb-node-c11:
    vlan1068:
      address: 172.23.60.67
      netmask: /32
    vlan1338:
      address: 172.23.69.109
      netmask: /32
  nb-repo:
    vlan1338:
      address: 172.23.69.140
      netmask: /32
  nb-sai:
    vlan1068:
      address: 172.23.60.7
      netmask: /32
    vlan1073:
      address: 172.23.14.213
      netmask: /32
    vlan1338:
      address: 172.23.69.155
      netmask: /32
    vlan985:
      address: 172.23.59.171
      netmask: /32
  nb-transfer:
    vlan1338:
      address: 172.23.69.27
      netmask: /32
      publicly_exposed: true  # This internal IP is linked to a public (floating) IP.
    vlan16:
      address: 195.169.22.166
      netmask: /32
      fqdn: 'nb-transfer.hpc.rug.nl'
  nibbler:
    nb_internal_management:
      address: 10.10.1.222
      netmask: /32
    vlan1068:
      address: 172.23.60.4
      netmask: /32
    vlan1073:
      address: 172.23.14.232
      netmask: /32
    vlan1338:
      address: 172.23.69.136
      netmask: /32
    vlan985:
      address: 172.23.59.144
      netmask: /32
  tunnel:
    vlan1338:
      address: 172.23.69.43
      netmask: /32
      publicly_exposed: true  # This internal IP is linked to a public (floating) IP.
    vlan16:
      address: 195.169.22.136
      netmask: /32
      fqdn: 'tunnel.hpc.rug.nl'
  nb_internal_management-vlan16-router:
    nb_internal_management:
      address: 10.10.1.1
      netmask: /32
    vlan16:
      address: 195.169.22.148
      netmask: /32
      fqdn: 'NXDOMAIN'
  vlan1338-vlan16-router:
    vlan1338:
      address: 172.23.69.1
      netmask: /32
    vlan16:
      address: 195.169.22.58
      netmask: /32
      fqdn: 'NXDOMAIN'
...
