---
#
# Jumphosts from other stack-name infra groups.
# We will use the hostnames for these jumphosts when creating the signed host keys with the ssh_host_signer role.
#
external_jumphosts:
  - group: gearshift_cluster
    hosts:
    - hostname: airlock
      network: vlan16
  - group: talos_cluster
    hosts:
      - hostname: reception
        network: vlan16
  - group: hyperchicken_cluster
    hosts:
      - hostname: portal
        network: public
  - group: fender_cluster
    hosts:
      - hostname: corridor
        network: public
  - group: nibbler_cluster
    hosts:
      - hostname: tunnel
        network: vlan16
  - group: vaxtron_cluster
    hosts:
      - hostname: foyer
        network: external
  - group: wingedhelix_cluster
    hosts:
      - hostname: wh-porch
        network: vlan16
  - group: betabarrel_cluster
    hosts:
      - hostname: bb-porch
        network: vlan16
  - group: copperfist_cluster
    hosts:
      - hostname: cf-porch
        network: external
...