---
- name: Check if system needs to be restarted
  ansible.builtin.command: '/bin/needs-restarting -r'
  register: needs_restarting
  failed_when: 'needs_restarting.rc > 1'
  changed_when: 'needs_restarting.rc == 1'
  become: true
  notify: reboot_by_gpu_role

- name: Copy blacklist-nouveau.conf file into modprobe.d to disable Nouveau drivers
  ansible.builtin.copy:
    src: blacklist-nouveau.conf
    dest: /etc/modprobe.d/blacklist-nouveau.conf
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: reboot_by_gpu_role

#
# Workaround: Disable the Kernel Address Space Layout Randomization (KASLR) security feature
# for GPUs that use the CUDA memory management feature "Heterogeneous Memory Management (HMM)" for
# "NVIDIA Unified Virtual Memory (UVM)", which currently crashes machines when KASLR is enabled.
#
# See https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#known-issues
#
- name: "Workaround - disable KASLR or {{ gpu_type }} GPUs that use NVIDIA HMM for NVIDIA UVM."
  ansible.builtin.include_tasks: disable_kaslr.yml
  when:
    - gpu_count|default(0) >= 1
    - gpu_type == 'rtx6000'

- name: Reboot system if needed
  ansible.builtin.meta: flush_handlers

- name: Gather facts to get the latest kernel version
  ansible.builtin.setup:
  become: true

- name: Install yum requirements for gpu driver installation
  ansible.builtin.package:
    state: 'installed'
    update_cache: true
    name:
      - 'kernel-devel-{{ ansible_facts.kernel }}'
      - tar
      - bzip2
      - make
      - automake
      - gcc
      - gcc-c++
      - pciutils
      - elfutils-libelf-devel
      - libglvnd-devel
      - bind-utils
      - wget
  become: true

- name: Download GPU driver installation file.
  ansible.builtin.get_url:
    url: "{{ gpu_url_dir }}/{{ gpu_runfile }}"
    dest: '/root/{{ gpu_runfile }}'
    mode: '0700'
  become: true

- name: Install GPU driver.
  ansible.builtin.command:
    cmd: |
         "/root/{{ gpu_runfile }}" --silent --kernel-module-type="{{ gpu_kernel_module_type | default('open') }}"
  register: install_result
  failed_when: install_result.rc != 0
  changed_when: true
  notify: reboot_by_gpu_role
  become: true

- name: Disable NVIDIA GSP firmware.
  ansible.builtin.copy:
    dest: /etc/modprobe.d/nvidia-gsp.conf
    content: "options nvidia NVreg_EnableGpuFirmware=0"
    owner: root
    group: root
    mode: '0644'
  when: gpu_type == 'a40'
  notify:
    - dracut
    - reboot_by_gpu_role
  become: true

- name: Flush handlers.
  ansible.builtin.meta: flush_handlers

- name: Remove installation file.
  ansible.builtin.file:
    path: '/root/{{ gpu_runfile }}'
    state: absent
  become: true
...
